
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Creacion del tablas de estado
CREATE TABLE FIDE_ESTADO_TB (
    ID_ESTADO NUMBER PRIMARY KEY,
    NOMBRE_ESTADO VARCHAR2(100) NOT NULL,
    CATEGORIA VARCHAR2(100)
);
/



-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de sectores geográficos de servicio
CREATE TABLE FIDE_SECTOR_TB (
    ID_SECTOR NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION  VARCHAR2(255),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_SECTOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
  
  
  
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_SECTOR_TB_ID_ESTADO_IDX ON FIDE_SECTOR_TB(ID_ESTADO);
/




-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de puestos de trabajo del personal
CREATE TABLE FIDE_PUESTO_TB (
    ID_PUESTO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(255),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_PUESTO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
  
  
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_PUESTO_TB_ID_ESTADO_IDX ON FIDE_PUESTO_TB(ID_ESTADO);
/





-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de métodos de pago disponibles
CREATE TABLE FIDE_METODO_PAGO_TB (
    ID_METODO_PAGO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(255),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_METODO_PAGO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_METODO_PAGO_TB_ID_ESTADO_IDX ON FIDE_METODO_PAGO_TB(ID_ESTADO);
/




-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de tipos de avería registrados en el sistema
CREATE TABLE FIDE_TIPO_AVERIA_TB (
    ID_TIPO_AVERIA NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(255),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_TIPO_AVERIA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_TIPO_AVERIA_TB_ID_ESTADO_IDX ON FIDE_TIPO_AVERIA_TB(ID_ESTADO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de tipos de medidor de agua
CREATE TABLE FIDE_TIPO_MEDIDOR_TB (
    ID_TIPO_MEDIDOR NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(255),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_TIPO_MEDIDOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_TIPO_MEDIDOR_TB_ID_ESTADO_IDX ON FIDE_TIPO_MEDIDOR_TB(ID_ESTADO);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de tipos de orden de trabajo
CREATE TABLE FIDE_TIPO_ORDEN_TRABAJO_TB (
    ID_TIPO_ORDEN_TRABAJO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(255),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_TIPO_ORDEN_TRABAJO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/



-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_TIPO_ORDEN_TRABAJO_TB_ID_ESTADO_IDX ON FIDE_TIPO_ORDEN_TRABAJO_TB(ID_ESTADO);
/





-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de unidades de medida para el inventario
CREATE TABLE FIDE_UNIDAD_MEDIDA_TB (
    ID_UNIDAD_MEDIDA NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    ABREVIATURA VARCHAR2(20),
    DESCRIPCION VARCHAR2(255),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_UNIDAD_MEDIDA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_UNIDAD_MEDIDA_TB_ID_ESTADO_IDX ON FIDE_UNIDAD_MEDIDA_TB(ID_ESTADO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de tarifas de cobro por consumo de agua
CREATE TABLE FIDE_TARIFA_TB (
    ID_TARIFA NUMBER PRIMARY KEY,
    NOMBRE_TARIFA VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(255),
    MONTO_BASE NUMBER(12,2),
    PRECIO_M3 NUMBER(12,4),
    CONSUMO_MINIMO_M3 NUMBER(12,4),
    CONSUMO_MAXIMO_M3 NUMBER(12,4),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_TARIFA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_TARIFA_TB_ID_ESTADO_IDX ON FIDE_TARIFA_TB(ID_ESTADO);
/
  
  
  
  
  
  
  
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice para consultas de vigencia de tarifa
CREATE INDEX FIDE_TARIFA_TB_FECHAS_IDX ON FIDE_TARIFA_TB(FECHA_INICIO, FECHA_FIN);
/




-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de países para abonados
CREATE TABLE FIDE_PAIS_ABONADO_TB (
    ID_PAIS NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de provincias para abonados
CREATE TABLE FIDE_PROVINCIA_ABONADO_TB (
    ID_PROVINCIA NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de cantones para abonados
CREATE TABLE FIDE_CANTON_ABONADO_TB (
    ID_CANTON NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100)NOT NULL
);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de distritos para abonados
CREATE TABLE FIDE_DISTRITO_ABONADO_TB (
    ID_DISTRITO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);
/


-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de países para empleados
CREATE TABLE FIDE_PAIS_EMPLEADO_TB (
    ID_PAIS NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de provincias para empleados
CREATE TABLE FIDE_PROVINCIA_EMPLEADO_TB(
    ID_PROVINCIA NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);
/



-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de cantones para empleados
CREATE TABLE FIDE_CANTON_EMPLEADO_TB (
    ID_CANTON NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de distritos para empleados
CREATE TABLE FIDE_DISTRITO_EMPLEADO_TB (
    ID_DISTRITO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de países para proveedores
CREATE TABLE FIDE_PAIS_PROVEEDOR_TB (
    ID_PAIS NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de provincias para proveedores
CREATE TABLE FIDE_PROVINCIA_PROVEEDOR_TB (
    ID_PROVINCIA NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);
/


-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de cantones para proveedores
CREATE TABLE FIDE_CANTON_PROVEEDOR_TB (
    ID_CANTON NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de distritos para proveedores
CREATE TABLE FIDE_DISTRITO_PROVEEDOR_TB (
    ID_DISTRITO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de abonados del servicio de agua
CREATE TABLE FIDE_ABONADO_TB (
    ID_ABONADO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100)   NOT NULL,
    APELLIDO_PATERNO VARCHAR2(100),
    APELLIDO_MATERNO VARCHAR2(100),
    ID_SECTOR NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_ABONADO_TB_ID_SECTOR_FK FOREIGN KEY (ID_SECTOR) REFERENCES FIDE_SECTOR_TB(ID_SECTOR),
    CONSTRAINT FIDE_ABONADO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de sector
CREATE INDEX FIDE_ABONADO_TB_ID_SECTOR_IDX ON FIDE_ABONADO_TB(ID_SECTOR);
/
  
  
  
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_ABONADO_TB_ID_ESTADO_IDX ON FIDE_ABONADO_TB(ID_ESTADO);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice para búsquedas por nombre del abonado
CREATE INDEX FIDE_ABONADO_TB_NOMBRE_IDX ON FIDE_ABONADO_TB(APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de empleados de la organización
CREATE TABLE FIDE_EMPLEADO_TB (
    ID_EMPLEADO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(100),
    APELLIDO_MATERNO VARCHAR2(100),
    ID_PUESTO NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_EMPLEADO_TB_ID_PUESTO_FK FOREIGN KEY (ID_PUESTO) REFERENCES FIDE_PUESTO_TB(ID_PUESTO),
    CONSTRAINT FIDE_EMPLEADO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de puesto
CREATE INDEX FIDE_EMPLEADO_TB_ID_PUESTO_IDX ON FIDE_EMPLEADO_TB(ID_PUESTO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_EMPLEADO_TB_ID_ESTADO_IDX ON FIDE_EMPLEADO_TB(ID_ESTADO);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estadoÍndice para búsquedas por nombre del empleado
CREATE INDEX FIDE_EMPLEADO_TB_NOMBRE_IDX ON FIDE_EMPLEADO_TB(APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de proveedores de materiales y servicios
CREATE TABLE FIDE_PROVEEDOR_TB (
    ID_PROVEEDOR NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_PROVEEDOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_PROVEEDOR_TB_ID_ESTADO_IDX ON FIDE_PROVEEDOR_TB(ID_ESTADO);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice para búsquedas por nombre del proveedor
CREATE INDEX FIDE_PROVEEDOR_TB_NOMBRE_IDX ON FIDE_PROVEEDOR_TB(NOMBRE);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:Tabla de correos electrónicos de abonados
CREATE TABLE FIDE_CORREO_ABONADO_TB (
    ID_ABONADO NUMBER NOT NULL,
    CORREO VARCHAR2(150) NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_CORREO_ABONADO_TB_PK PRIMARY KEY (ID_ABONADO, CORREO),
    CONSTRAINT FIDE_CORREO_ABONADO_TB_ID_ABONADO_FK FOREIGN KEY (ID_ABONADO) REFERENCES FIDE_ABONADO_TB(ID_ABONADO),
    CONSTRAINT FIDE_CORREO_ABONADO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_CORREO_ABONADO_TB_ID_ESTADO_IDX ON FIDE_CORREO_ABONADO_TB(ID_ESTADO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de correos electrónicos de empleados
CREATE TABLE FIDE_CORREO_EMPLEADO_TB (
    ID_EMPLEADO NUMBER NOT NULL,
    CORREO VARCHAR2(150) NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_CORREO_EMPLEADO_TB_PK PRIMARY KEY (ID_EMPLEADO, CORREO),
    CONSTRAINT FIDE_CORREO_EMPLEADO_TB_ID_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES FIDE_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FIDE_CORREO_EMPLEADO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_CORREO_EMPLEADO_TB_ID_ESTADO_IDX ON FIDE_CORREO_EMPLEADO_TB(ID_ESTADO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de correos electrónicos de proveedores
CREATE TABLE FIDE_CORREO_PROVEEDOR_TB (
    ID_PROVEEDOR NUMBER NOT NULL,
    CORREO VARCHAR2(150) NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_CORREO_PROVEEDOR_TB_PK PRIMARY KEY (ID_PROVEEDOR, CORREO),
    CONSTRAINT FIDE_CORREO_PROVEEDOR_TB_ID_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES FIDE_PROVEEDOR_TB(ID_PROVEEDOR),
    CONSTRAINT FIDE_CORREO_PROVEEDOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_CORREO_PROVEEDOR_TB_ID_ESTADO_IDX ON FIDE_CORREO_PROVEEDOR_TB(ID_ESTADO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de teléfonos de abonados
CREATE TABLE FIDE_TELEFONO_ABONADO_TB (
    ID_ABONADO NUMBER NOT NULL,
    NUMERO VARCHAR2(30) NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_TELEFONO_ABONADO_TB_PK PRIMARY KEY (ID_ABONADO, NUMERO),
    CONSTRAINT FIDE_TELEFONO_ABONADO_TB_ID_ABONADO_FK FOREIGN KEY (ID_ABONADO) REFERENCES FIDE_ABONADO_TB(ID_ABONADO),
    CONSTRAINT FIDE_TELEFONO_ABONADO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_TELEFONO_ABONADO_TB_ID_ESTADO_IDX ON FIDE_TELEFONO_ABONADO_TB(ID_ESTADO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de teléfonos de empleados
CREATE TABLE FIDE_TELEFONO_EMPLEADO_TB (
    ID_EMPLEADO NUMBER NOT NULL,
    NUMERO VARCHAR2(30) NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_TELEFONO_EMPLEADO_TB_PK PRIMARY KEY (ID_EMPLEADO, NUMERO),
    CONSTRAINT FIDE_TELEFONO_EMPLEADO_TB_ID_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES FIDE_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FIDE_TELEFONO_EMPLEADO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:Índice sobre la llave foránea de estado
CREATE INDEX FIDE_TELEFONO_EMPLEADO_TB_ID_ESTADO_IDX ON FIDE_TELEFONO_EMPLEADO_TB(ID_ESTADO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de teléfonos de proveedores
CREATE TABLE FIDE_TELEFONO_PROVEEDOR_TB (
    ID_PROVEEDOR NUMBER NOT NULL,
    NUMERO VARCHAR2(30) NOT NULL,
    ID_ESTADO  NUMBER NOT NULL,
    CONSTRAINT FIDE_TELEFONO_PROVEEDOR_TB_PK PRIMARY KEY (ID_PROVEEDOR, NUMERO),
    CONSTRAINT FIDE_TELEFONO_PROVEEDOR_TB_ID_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES FIDE_PROVEEDOR_TB(ID_PROVEEDOR),
    CONSTRAINT FIDE_TELEFONO_PROVEEDOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_TELEFONO_PROVEEDOR_TB_ID_ESTADO_IDX ON FIDE_TELEFONO_PROVEEDOR_TB(ID_ESTADO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de direcciones de abonados
CREATE TABLE FIDE_DIRECCIONES_ABONADO_TB (
    ID_ABONADO NUMBER NOT NULL,
    ID_PAIS NUMBER NOT NULL,
    ID_PROVINCIA NUMBER NOT NULL,
    ID_CANTON NUMBER NOT NULL,
    ID_DISTRITO NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_PK PRIMARY KEY (ID_ABONADO, ID_PAIS, ID_PROVINCIA, ID_CANTON, ID_DISTRITO),
    CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_ID_ABONADO_FK FOREIGN KEY (ID_ABONADO) REFERENCES FIDE_ABONADO_TB(ID_ABONADO),
    CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_ID_PAIS_FK FOREIGN KEY (ID_PAIS) REFERENCES FIDE_PAIS_ABONADO_TB(ID_PAIS),
    CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_ID_PROVINCIA_FK FOREIGN KEY (ID_PROVINCIA) REFERENCES FIDE_PROVINCIA_ABONADO_TB(ID_PROVINCIA),
    CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_ID_CANTON_FK FOREIGN KEY (ID_CANTON) REFERENCES FIDE_CANTON_ABONADO_TB(ID_CANTON),
    CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_ID_DISTRITO_FK FOREIGN KEY (ID_DISTRITO) REFERENCES FIDE_DISTRITO_ABONADO_TB(ID_DISTRITO),
    CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: -Índice sobre la llave foránea de estado
CREATE INDEX FIDE_DIRECCIONES_ABONADO_TB_ID_ESTADO_IDX ON FIDE_DIRECCIONES_ABONADO_TB(ID_ESTADO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de direcciones de empleados
CREATE TABLE FIDE_DIRECCIONES_EMPLEADO_TB (
    ID_EMPLEADO NUMBER NOT NULL,
    ID_PAIS NUMBER  NOT NULL,
    ID_PROVINCIA NUMBER NOT NULL,
    ID_CANTON NUMBER NOT NULL,
    ID_DISTRITO NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_PK PRIMARY KEY (ID_EMPLEADO, ID_PAIS, ID_PROVINCIA, ID_CANTON, ID_DISTRITO),
    CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_ID_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES FIDE_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_ID_PAIS_FK FOREIGN KEY (ID_PAIS) REFERENCES FIDE_PAIS_EMPLEADO_TB(ID_PAIS),
    CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_ID_PROVINCIA_FK FOREIGN KEY (ID_PROVINCIA) REFERENCES FIDE_PROVINCIA_EMPLEADO_TB(ID_PROVINCIA),
    CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_ID_CANTON_FK FOREIGN KEY (ID_CANTON) REFERENCES FIDE_CANTON_EMPLEADO_TB(ID_CANTON),
    CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_ID_DISTRITO_FK FOREIGN KEY (ID_DISTRITO) REFERENCES FIDE_DISTRITO_EMPLEADO_TB(ID_DISTRITO),
    CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:Índice sobre la llave foránea de estado
CREATE INDEX FIDE_DIRECCIONES_EMPLEADO_TB_ID_ESTADO_IDX ON FIDE_DIRECCIONES_EMPLEADO_TB(ID_ESTADO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de direcciones de proveedores
CREATE TABLE FIDE_DIRECCIONES_PROVEEDOR_TB (
    ID_PROVEEDOR NUMBER NOT NULL,
    ID_PAIS NUMBER NOT NULL,
    ID_PROVINCIA NUMBER NOT NULL,
    ID_CANTON NUMBER NOT NULL,
    ID_DISTRITO NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_PK PRIMARY KEY (ID_PROVEEDOR, ID_PAIS, ID_PROVINCIA, ID_CANTON, ID_DISTRITO),
    CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_ID_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES FIDE_PROVEEDOR_TB(ID_PROVEEDOR),
    CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_ID_PAIS_FK FOREIGN KEY (ID_PAIS) REFERENCES FIDE_PAIS_PROVEEDOR_TB(ID_PAIS),
    CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_ID_PROVINCIA_FK FOREIGN KEY (ID_PROVINCIA) REFERENCES FIDE_PROVINCIA_PROVEEDOR_TB(ID_PROVINCIA),
    CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_ID_CANTON_FK FOREIGN KEY (ID_CANTON) REFERENCES FIDE_CANTON_PROVEEDOR_TB(ID_CANTON),
    CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_ID_DISTRITO_FK FOREIGN KEY (ID_DISTRITO) REFERENCES FIDE_DISTRITO_PROVEEDOR_TB(ID_DISTRITO),
    CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_DIRECCIONES_PROVEEDOR_TB_ID_ESTADO_IDX ON FIDE_DIRECCIONES_PROVEEDOR_TB(ID_ESTADO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de medidores de agua instalados en los abonados
CREATE TABLE FIDE_MEDIDOR_TB (
    ID_MEDIDOR NUMBER PRIMARY KEY,
    NUMERO_MEDIDOR VARCHAR2(50) NOT NULL,
    FECHA_INSTALACION DATE,
    MARCA VARCHAR2(100),
    ID_TIPO_MEDIDOR NUMBER NOT NULL,
    ID_ABONADO NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_MEDIDOR_TB_ID_TIPO_MEDIDOR_FK FOREIGN KEY (ID_TIPO_MEDIDOR) REFERENCES FIDE_TIPO_MEDIDOR_TB(ID_TIPO_MEDIDOR),
    CONSTRAINT FIDE_MEDIDOR_TB_ID_ABONADO_FK FOREIGN KEY (ID_ABONADO) REFERENCES FIDE_ABONADO_TB(ID_ABONADO),
    CONSTRAINT FIDE_MEDIDOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de tipo de medidor
CREATE INDEX FIDE_MEDIDOR_TB_ID_TIPO_MEDIDOR_IDX ON FIDE_MEDIDOR_TB(ID_TIPO_MEDIDOR);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:Índice sobre la llave foránea de abonado
  
CREATE INDEX FIDE_MEDIDOR_TB_ID_ABONADO_IDX ON FIDE_MEDIDOR_TB(ID_ABONADO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:
CREATE INDEX FIDE_MEDIDOR_TB_ID_ESTADO_IDX ON FIDE_MEDIDOR_TB(ID_ESTADO);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice para búsquedas por número de medidor
CREATE INDEX FIDE_MEDIDOR_TB_NUMERO_IDX ON FIDE_MEDIDOR_TB(NUMERO_MEDIDOR);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de lecturas de consumo registradas por los empleados
CREATE TABLE FIDE_LECTURA_TB (
    ID_LECTURA NUMBER PRIMARY KEY,
    FECHA_LECTURA DATE NOT NULL,
    LECTURA_ANTERIOR NUMBER(12,4),
    LECTURA_ACTUAL NUMBER(12,4) NOT NULL,
    CONSUMO_M3 NUMBER(12,4),
    ID_MEDIDOR NUMBER NOT NULL,
    ID_EMPLEADO NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_LECTURA_TB_ID_MEDIDOR_FK FOREIGN KEY (ID_MEDIDOR) REFERENCES FIDE_MEDIDOR_TB(ID_MEDIDOR),
    CONSTRAINT FIDE_LECTURA_TB_ID_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES FIDE_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FIDE_LECTURA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de medidor
CREATE INDEX FIDE_LECTURA_TB_ID_MEDIDOR_IDX ON FIDE_LECTURA_TB(ID_MEDIDOR);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de empleado
CREATE INDEX FIDE_LECTURA_TB_ID_EMPLEADO_IDX ON FIDE_LECTURA_TB(ID_EMPLEADO);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_LECTURA_TB_ID_ESTADO_IDX ON FIDE_LECTURA_TB(ID_ESTADO);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:Índice para consultas de lecturas por período
CREATE INDEX FIDE_LECTURA_TB_FECHA_IDX ON FIDE_LECTURA_TB(FECHA_LECTURA);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:Tabla de facturas emitidas a los abonados
CREATE TABLE FIDE_FACTURA_TB (
    ID_FACTURA NUMBER PRIMARY KEY,
    NUMERO_FACTURA VARCHAR2(50)    NOT NULL,
    FECHA_FACTURA DATE NOT NULL,
    FECHA_VENCIMIENTO DATE,
    SUBTOTAL NUMBER(12,2),
    IMPUESTOS NUMBER(12,2),
    TOTAL NUMBER(12,2),
    ID_ABONADO NUMBER NOT NULL,
    ID_LECTURA NUMBER NOT NULL,
    ID_TARIFA NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_FACTURA_TB_ID_ABONADO_FK FOREIGN KEY (ID_ABONADO) REFERENCES FIDE_ABONADO_TB(ID_ABONADO),
    CONSTRAINT FIDE_FACTURA_TB_ID_LECTURA_FK FOREIGN KEY (ID_LECTURA) REFERENCES FIDE_LECTURA_TB(ID_LECTURA),
    CONSTRAINT FIDE_FACTURA_TB_ID_TARIFA_FK FOREIGN KEY (ID_TARIFA) REFERENCES FIDE_TARIFA_TB(ID_TARIFA),
    CONSTRAINT FIDE_FACTURA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:Índice sobre la llave foránea de abonado
CREATE INDEX FIDE_FACTURA_TB_ID_ABONADO_IDX ON FIDE_FACTURA_TB(ID_ABONADO);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de lectura
CREATE INDEX FIDE_FACTURA_TB_ID_LECTURA_IDX ON FIDE_FACTURA_TB(ID_LECTURA);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de tarifa
CREATE INDEX FIDE_FACTURA_TB_ID_TARIFA_IDX ON FIDE_FACTURA_TB(ID_TARIFA);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_FACTURA_TB_ID_ESTADO_IDX ON FIDE_FACTURA_TB(ID_ESTADO);
/

  -- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice para búsquedas por número de factura
CREATE INDEX FIDE_FACTURA_TB_NUMERO_IDX ON FIDE_FACTURA_TB(NUMERO_FACTURA);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice para reportes por fecha de emisión
CREATE INDEX FIDE_FACTURA_TB_FECHA_IDX ON FIDE_FACTURA_TB(FECHA_FACTURA);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice para control de facturas por vencer
CREATE INDEX FIDE_FACTURA_TB_VENCIMIENTO_IDX ON FIDE_FACTURA_TB(FECHA_VENCIMIENTO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de líneas de detalle de cada factura de abonado
CREATE TABLE FIDE_DETALLE_FACTURA_TB (
    ID_DETALLE_FACTURA NUMBER PRIMARY KEY,
    CONCEPTO VARCHAR2(255) NOT NULL,
    CANTIDAD NUMBER(12,4),
    PRECIO_UNITARIO NUMBER(12,4),
    SUBTOTAL NUMBER(12,2),
    ID_FACTURA NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_DETALLE_FACTURA_TB_ID_FACTURA_FK FOREIGN KEY (ID_FACTURA) REFERENCES FIDE_FACTURA_TB(ID_FACTURA),
    CONSTRAINT FIDE_DETALLE_FACTURA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/





-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:Índice sobre la llave foránea de factura
CREATE INDEX FIDE_DETALLE_FACTURA_TB_ID_FACTURA_IDX ON FIDE_DETALLE_FACTURA_TB(ID_FACTURA);
/

: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_DETALLE_FACTURA_TB_ID_ESTADO_IDX ON FIDE_DETALLE_FACTURA_TB(ID_ESTADO);
/


-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de pagos realizados por los abonados
CREATE TABLE FIDE_PAGO_TB (
    ID_PAGO NUMBER PRIMARY KEY,
    MONTO NUMBER(12,2) NOT NULL,
    FECHA_PAGO DATE NOT NULL,
    REFERENCIA VARCHAR2(100),
    ID_FACTURA NUMBER NOT NULL,
    ID_METODO_PAGO  NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_PAGO_TB_ID_FACTURA_FK FOREIGN KEY (ID_FACTURA) REFERENCES FIDE_FACTURA_TB(ID_FACTURA),
    CONSTRAINT FIDE_PAGO_TB_ID_METODO_PAGO_FK FOREIGN KEY (ID_METODO_PAGO) REFERENCES FIDE_METODO_PAGO_TB(ID_METODO_PAGO),
    CONSTRAINT FIDE_PAGO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/



-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de factura
CREATE INDEX FIDE_PAGO_TB_ID_FACTURA_IDX ON FIDE_PAGO_TB(ID_FACTURA);
/



-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de método de pago
CREATE INDEX FIDE_PAGO_TB_ID_METODO_PAGO_IDX ON FIDE_PAGO_TB(ID_METODO_PAGO);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_PAGO_TB_ID_ESTADO_IDX ON FIDE_PAGO_TB(ID_ESTADO);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice para reportes de pagos por fecha
CREATE INDEX FIDE_PAGO_TB_FECHA_IDX ON FIDE_PAGO_TB(FECHA_PAGO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de artículos del inventario
CREATE TABLE FIDE_INVENTARIO_TB (
    ID_INVENTARIO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(255),
    ID_UNIDAD_MEDIDA NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_INVENTARIO_TB_ID_UNIDAD_MEDIDA_FK FOREIGN KEY (ID_UNIDAD_MEDIDA) REFERENCES FIDE_UNIDAD_MEDIDA_TB(ID_UNIDAD_MEDIDA),
    CONSTRAINT FIDE_INVENTARIO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/




-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:
CREATE INDEX FIDE_INVENTARIO_TB_ID_UNIDAD_MEDIDA_IDX ON FIDE_INVENTARIO_TB(ID_UNIDAD_MEDIDA);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:
CREATE INDEX FIDE_INVENTARIO_TB_ID_ESTADO_IDX ON FIDE_INVENTARIO_TB(ID_ESTADO);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:
CREATE INDEX FIDE_INVENTARIO_TB_NOMBRE_IDX ON FIDE_INVENTARIO_TB(NOMBRE);
/








-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:
CREATE TABLE FIDE_ALMACEN_INVENTARIO_TB (
    ID_ALMACEN_INVENTARIO NUMBER PRIMARY KEY,
    STOCK_ACTUAL NUMBER(12,4),
    STOCK_MIN NUMBER(12,4),
    ID_INVENTARIO NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_ALMACEN_INVENTARIO_TB_ID_INVENTARIO_FK FOREIGN KEY (ID_INVENTARIO) REFERENCES FIDE_INVENTARIO_TB(ID_INVENTARIO),
    CONSTRAINT FIDE_ALMACEN_INVENTARIO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/



-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:
CREATE INDEX FIDE_ALMACEN_INVENTARIO_TB_ID_INVENTARIO_IDX ON FIDE_ALMACEN_INVENTARIO_TB(ID_INVENTARIO);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:
CREATE INDEX FIDE_ALMACEN_INVENTARIO_TB_ID_ESTADO_IDX ON FIDE_ALMACEN_INVENTARIO_TB(ID_ESTADO);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:
CREATE INDEX FIDE_ALMACEN_INVENTARIO_TB_STOCK_IDX ON FIDE_ALMACEN_INVENTARIO_TB(STOCK_ACTUAL, STOCK_MIN);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:
CREATE TABLE FIDE_PROVEEDOR_INVENTARIO_TB (
    ID_PROVEEDOR NUMBER NOT NULL,
    ID_INVENTARIO NUMBER NOT NULL,
    CONSTRAINT FIDE_PROVEEDOR_INVENTARIO_TB_PK PRIMARY KEY (ID_PROVEEDOR, ID_INVENTARIO),
    CONSTRAINT FIDE_PROVEEDOR_INVENTARIO_TB_ID_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES FIDE_PROVEEDOR_TB(ID_PROVEEDOR),
    CONSTRAINT FIDE_PROVEEDOR_INVENTARIO_TB_ID_INVENTARIO_FK FOREIGN KEY (ID_INVENTARIO) REFERENCES FIDE_INVENTARIO_TB(ID_INVENTARIO)
);
/
  
  

  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: -Índice sobre la llave foránea de inventario
CREATE INDEX FIDE_PROVEEDOR_INVENTARIO_TB_ID_INVENTARIO_IDX ON FIDE_PROVEEDOR_INVENTARIO_TB(ID_INVENTARIO);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de proveedor
CREATE INDEX FIDE_PROVEEDOR_INVENTARIO_TB_ID_PROVEEDOR_IDX ON FIDE_PROVEEDOR_INVENTARIO_TB(ID_PROVEEDOR);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de facturas recibidas de proveedores
CREATE TABLE FIDE_FACTURA_PROVEEDOR_TB (
    ID_FACTURA_PROVEEDOR NUMBER PRIMARY KEY,
    NUMERO_FACTURA VARCHAR2(50)    NOT NULL,
    FECHA_FACTURA DATE NOT NULL,
    FECHA_VENCIMIENTO DATE,
    SUBTOTAL NUMBER(12,2),
    IMPUESTOS NUMBER(12,2),
    TOTAL NUMBER(12,2),
    ID_PROVEEDOR NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_FACTURA_PROVEEDOR_TB_ID_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES FIDE_PROVEEDOR_TB(ID_PROVEEDOR),
    CONSTRAINT FIDE_FACTURA_PROVEEDOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de proveedor
CREATE INDEX FIDE_FACTURA_PROVEEDOR_TB_ID_PROVEEDOR_IDX ON FIDE_FACTURA_PROVEEDOR_TB(ID_PROVEEDOR);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_FACTURA_PROVEEDOR_TB_ID_ESTADO_IDX ON FIDE_FACTURA_PROVEEDOR_TB(ID_ESTADO);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice para búsquedas por número de factura de proveedor
CREATE INDEX FIDE_FACTURA_PROVEEDOR_TB_NUMERO_IDX ON FIDE_FACTURA_PROVEEDOR_TB(NUMERO_FACTURA);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice para reportes por fecha de emisión
CREATE INDEX FIDE_FACTURA_PROVEEDOR_TB_FECHA_IDX ON FIDE_FACTURA_PROVEEDOR_TB(FECHA_FACTURA);
/




-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:Índice para control de facturas por vencer
CREATE INDEX FIDE_FACTURA_PROVEEDOR_TB_VENCIMIENTO_IDX ON FIDE_FACTURA_PROVEEDOR_TB(FECHA_VENCIMIENTO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de líneas de detalle de cada factura de proveedor
CREATE TABLE FIDE_DETALLE_FACTURA_PROVEEDOR_TB (
    ID_DETALLE_FACTURA_PROVEEDOR NUMBER PRIMARY KEY,
    CONCEPTO VARCHAR2(255) NOT NULL,
    CANTIDAD NUMBER(12,4),
    PRECIO_UNITARIO NUMBER(12,4),
    SUBTOTAL NUMBER(12,2),
    ID_FACTURA_PROVEEDOR NUMBER NOT NULL,
    ID_INVENTARIO NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_DETALLE_FACTURA_PROVEEDOR_TB_ID_FACTURA_PROVEEDOR_FK FOREIGN KEY (ID_FACTURA_PROVEEDOR) REFERENCES FIDE_FACTURA_PROVEEDOR_TB(ID_FACTURA_PROVEEDOR),
    CONSTRAINT FIDE_DETALLE_FACTURA_PROVEEDOR_TB_ID_INVENTARIO_FK FOREIGN KEY (ID_INVENTARIO) REFERENCES FIDE_INVENTARIO_TB(ID_INVENTARIO),
    CONSTRAINT FIDE_DETALLE_FACTURA_PROVEEDOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de factura proveedor
CREATE INDEX FIDE_DETALLE_FACTURA_PROVEEDOR_TB_ID_FACTURA_PROVEEDOR_IDX ON FIDE_DETALLE_FACTURA_PROVEEDOR_TB(ID_FACTURA_PROVEEDOR);
/






-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de inventario
CREATE INDEX FIDE_DETALLE_FACTURA_PROVEEDOR_TB_ID_INVENTARIO_IDX ON FIDE_DETALLE_FACTURA_PROVEEDOR_TB(ID_INVENTARIO);
/


-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_DETALLE_FACTURA_PROVEEDOR_TB_ID_ESTADO_IDX ON FIDE_DETALLE_FACTURA_PROVEEDOR_TB(ID_ESTADO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de averías reportadas por los abonados
CREATE TABLE FIDE_AVERIA_TB (
    ID_AVERIA NUMBER PRIMARY KEY,
    FECHA_REPORTE DATE NOT NULL,
    DESCRIPCION VARCHAR2(500),
    UBICACION_REFERENCIA VARCHAR2(255),
    ID_ABONADO NUMBER NOT NULL,
    ID_SECTOR NUMBER NOT NULL,
    ID_TIPO_AVERIA NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_AVERIA_TB_ID_ABONADO_FK FOREIGN KEY (ID_ABONADO) REFERENCES FIDE_ABONADO_TB(ID_ABONADO),
    CONSTRAINT FIDE_AVERIA_TB_ID_SECTOR_FK FOREIGN KEY (ID_SECTOR) REFERENCES FIDE_SECTOR_TB(ID_SECTOR),
    CONSTRAINT FIDE_AVERIA_TB_ID_TIPO_AVERIA_FK FOREIGN KEY (ID_TIPO_AVERIA) REFERENCES FIDE_TIPO_AVERIA_TB(ID_TIPO_AVERIA),
    CONSTRAINT FIDE_AVERIA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:
CREATE INDEX FIDE_AVERIA_TB_ID_ABONADO_IDX ON FIDE_AVERIA_TB(ID_ABONADO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:
CREATE INDEX FIDE_AVERIA_TB_ID_SECTOR_IDX ON FIDE_AVERIA_TB(ID_SECTOR);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de tipo de avería
CREATE INDEX FIDE_AVERIA_TB_ID_TIPO_AVERIA_IDX ON FIDE_AVERIA_TB(ID_TIPO_AVERIA);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_AVERIA_TB_ID_ESTADO_IDX ON FIDE_AVERIA_TB(ID_ESTADO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice para reportes de averías por fecha de reporte
CREATE INDEX FIDE_AVERIA_TB_FECHA_IDX ON FIDE_AVERIA_TB(FECHA_REPORTE);
/


-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de órdenes de trabajo generadas para atender averías
CREATE TABLE FIDE_ORDEN_TRABAJO_TB (
    ID_ORDEN_TRABAJO NUMBER PRIMARY KEY,
    FECHA_ASIGNACION DATE,
    FECHA_CIERRE DATE,
    DESCRIPCION_TRABAJO VARCHAR2(500),
    OBSERVACIONES VARCHAR2(500),
    ID_AVERIA NUMBER NOT NULL,
    ID_TIPO_ORDEN_TRABAJO   NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_ORDEN_TRABAJO_TB_ID_AVERIA_FK FOREIGN KEY (ID_AVERIA) REFERENCES FIDE_AVERIA_TB(ID_AVERIA),
    CONSTRAINT FIDE_ORDEN_TRABAJO_TB_ID_TIPO_ORDEN_TRABAJO_FK FOREIGN KEY (ID_TIPO_ORDEN_TRABAJO) REFERENCES FIDE_TIPO_ORDEN_TRABAJO_TB(ID_TIPO_ORDEN_TRABAJO),
    CONSTRAINT FIDE_ORDEN_TRABAJO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de avería
CREATE INDEX FIDE_ORDEN_TRABAJO_TB_ID_AVERIA_IDX ON FIDE_ORDEN_TRABAJO_TB(ID_AVERIA);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de tipo de orden
CREATE INDEX FIDE_ORDEN_TRABAJO_TB_ID_TIPO_ORDEN_TRABAJO_IDX ON FIDE_ORDEN_TRABAJO_TB(ID_TIPO_ORDEN_TRABAJO);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de estado
CREATE INDEX FIDE_ORDEN_TRABAJO_TB_ID_ESTADO_IDX ON FIDE_ORDEN_TRABAJO_TB(ID_ESTADO);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice para consultas de órdenes por fecha de asignación
CREATE INDEX FIDE_ORDEN_TRABAJO_TB_FECHA_ASIGNACION_IDX ON FIDE_ORDEN_TRABAJO_TB(FECHA_ASIGNACION);
/



-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice para consultas de órdenes por fecha de cierre
CREATE INDEX FIDE_ORDEN_TRABAJO_TB_FECHA_CIERRE_IDX ON FIDE_ORDEN_TRABAJO_TB(FECHA_CIERRE);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla intermedia entre órdenes de trabajo y empleados asignados
CREATE TABLE FIDE_ORDEN_EMPLEADO_TB (
    ID_ORDEN_TRABAJO NUMBER  NOT NULL,
    ID_EMPLEADO NUMBER  NOT NULL,
    CONSTRAINT FIDE_ORDEN_EMPLEADO_TB_PK PRIMARY KEY (ID_ORDEN_TRABAJO, ID_EMPLEADO),
    CONSTRAINT FIDE_ORDEN_EMPLEADO_TB_ID_ORDEN_TRABAJO_FK FOREIGN KEY (ID_ORDEN_TRABAJO) REFERENCES FIDE_ORDEN_TRABAJO_TB(ID_ORDEN_TRABAJO),
    CONSTRAINT FIDE_ORDEN_EMPLEADO_TB_ID_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES FIDE_EMPLEADO_TB(ID_EMPLEADO)
);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de empleado
CREATE INDEX FIDE_ORDEN_EMPLEADO_TB_ID_EMPLEADO_IDX ON FIDE_ORDEN_EMPLEADO_TB(ID_EMPLEADO);
/
  
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:Índice sobre la llave foránea de orden de trabajo
CREATE INDEX FIDE_ORDEN_EMPLEADO_TB_ID_ORDEN_TRABAJO_IDX ON FIDE_ORDEN_EMPLEADO_TB(ID_ORDEN_TRABAJO);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla intermedia  entre órdenes de trabajo y materiales utilizados
CREATE TABLE FIDE_ORDEN_INVENTARIO_TB (
    ID_ORDEN_TRABAJO NUMBER  NOT NULL,
    ID_INVENTARIO NUMBER  NOT NULL,
    CONSTRAINT FIDE_ORDEN_INVENTARIO_TB_PK PRIMARY KEY (ID_ORDEN_TRABAJO, ID_INVENTARIO),
    CONSTRAINT FIDE_ORDEN_INVENTARIO_TB_ID_ORDEN_TRABAJO_FK FOREIGN KEY (ID_ORDEN_TRABAJO) REFERENCES FIDE_ORDEN_TRABAJO_TB(ID_ORDEN_TRABAJO),
    CONSTRAINT FIDE_ORDEN_INVENTARIO_TB_ID_INVENTARIO_FK FOREIGN KEY (ID_INVENTARIO) REFERENCES FIDE_INVENTARIO_TB(ID_INVENTARIO)
);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de inventario
CREATE INDEX FIDE_ORDEN_INVENTARIO_TB_ID_INVENTARIO_IDX ON FIDE_ORDEN_INVENTARIO_TB(ID_INVENTARIO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de orden de trabajo
CREATE INDEX FIDE_ORDEN_INVENTARIO_TB_ID_ORDEN_TRABAJO_IDX ON FIDE_ORDEN_INVENTARIO_TB(ID_ORDEN_TRABAJO);
/

-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de movimientos de entrada y salida del inventario
CREATE TABLE FIDE_MOVIMIENTO_INVENTARIO_TB (
    ID_MOVIMIENTO_INVENTARIO NUMBER PRIMARY KEY,
    TIPO VARCHAR2(50) NOT NULL,
    FECHA DATE NOT NULL,
    CANTIDAD NUMBER(12,4)    NOT NULL,
    MOTIVO VARCHAR2(255),
    ID_INVENTARIO NUMBER NOT NULL,
    ID_ORDEN_TRABAJO NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_TB_ID_INVENTARIO_FK FOREIGN KEY (ID_INVENTARIO) REFERENCES FIDE_INVENTARIO_TB(ID_INVENTARIO),
    CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_TB_ID_ORDEN_TRABAJO_FK FOREIGN KEY (ID_ORDEN_TRABAJO) REFERENCES FIDE_ORDEN_TRABAJO_TB(ID_ORDEN_TRABAJO),
    CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:  Índice sobre la llave foránea de inventario
CREATE INDEX FIDE_MOVIMIENTO_INVENTARIO_TB_ID_INVENTARIO_IDX ON FIDE_MOVIMIENTO_INVENTARIO_TB(ID_INVENTARIO);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice sobre la llave foránea de orden de trabajo
CREATE INDEX FIDE_MOVIMIENTO_INVENTARIO_TB_ID_ORDEN_TRABAJO_IDX ON FIDE_MOVIMIENTO_INVENTARIO_TB(ID_ORDEN_TRABAJO);
/
-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:  Índice sobre la llave foránea de estado
CREATE INDEX FIDE_MOVIMIENTO_INVENTARIO_TB_ID_ESTADO_IDX ON FIDE_MOVIMIENTO_INVENTARIO_TB(ID_ESTADO);
/


-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción:  Índice para reportes de movimientos por fecha
CREATE INDEX FIDE_MOVIMIENTO_INVENTARIO_TB_FECHA_IDX ON FIDE_MOVIMIENTO_INVENTARIO_TB(FECHA);
/


-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Índice para filtrar por tipo de movimiento (entrada/salida)
CREATE INDEX FIDE_MOVIMIENTO_INVENTARIO_TB_TIPO_IDX ON FIDE_MOVIMIENTO_INVENTARIO_TB(TIPO);
/





-- AUTORES: Integrates del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Commit normal
COMMIT;
/
