-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Catálogo central referenciado por todas las tablas
CREATE TABLE FIDE_ESTADO_TB (
    ID_ESTADO NUMBER CONSTRAINT FIDE_ESTADO_TB_ID_ESTADO_NN NOT NULL,
    NOMBRE_ESTADO VARCHAR2(100) CONSTRAINT FIDE_ESTADO_TB_NOMBRE_ESTADO_NN NOT NULL,
    CATEGORIA VARCHAR2(100),
    CONSTRAINT FIDE_ESTADO_TB_ID_ESTADO_PK PRIMARY KEY (ID_ESTADO)
);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de sectores geográficos de servicio
CREATE TABLE FIDE_SECTOR_TB (
    ID_SECTOR NUMBER CONSTRAINT FIDE_SECTOR_TB_ID_SECTOR_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_SECTOR_TB_NOMBRE_NN NOT NULL,
    DESCRIPCION VARCHAR2(255),
    ID_ESTADO NUMBER CONSTRAINT FIDE_SECTOR_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_SECTOR_TB_ID_SECTOR_PK PRIMARY KEY (ID_SECTOR),
    CONSTRAINT FIDE_SECTOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_SECTOR_TB_ID_ESTADO_IDX ON FIDE_SECTOR_TB(ID_ESTADO);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de puestos de trabajo del personal
CREATE TABLE FIDE_PUESTO_TB (
    ID_PUESTO NUMBER CONSTRAINT FIDE_PUESTO_TB_ID_PUESTO_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_PUESTO_TB_NOMBRE_NN NOT NULL,
    DESCRIPCION VARCHAR2(255),
    ID_ESTADO NUMBER CONSTRAINT FIDE_PUESTO_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_PUESTO_TB_ID_PUESTO_PK PRIMARY KEY (ID_PUESTO),
    CONSTRAINT FIDE_PUESTO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_PUESTO_TB_ID_ESTADO_IDX ON FIDE_PUESTO_TB(ID_ESTADO);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de métodos de pago disponibles
CREATE TABLE FIDE_METODO_PAGO_TB (
    ID_METODO_PAGO NUMBER CONSTRAINT FIDE_METODO_PAGO_TB_ID_METODO_PAGO_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_METODO_PAGO_TB_NOMBRE_NN NOT NULL,
    DESCRIPCION VARCHAR2(255),
    ID_ESTADO NUMBER CONSTRAINT FIDE_METODO_PAGO_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_METODO_PAGO_TB_ID_METODO_PAGO_PK PRIMARY KEY (ID_METODO_PAGO),
    CONSTRAINT FIDE_METODO_PAGO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_METODO_PAGO_TB_ID_ESTADO_IDX ON FIDE_METODO_PAGO_TB(ID_ESTADO);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de tipos de avería registrados en el sistema
CREATE TABLE FIDE_TIPO_AVERIA_TB (
    ID_TIPO_AVERIA NUMBER CONSTRAINT FIDE_TIPO_AVERIA_TB_ID_TIPO_AVERIA_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_TIPO_AVERIA_TB_NOMBRE_NN NOT NULL,
    DESCRIPCION VARCHAR2(255),
    ID_ESTADO NUMBER CONSTRAINT FIDE_TIPO_AVERIA_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_TIPO_AVERIA_TB_ID_TIPO_AVERIA_PK PRIMARY KEY (ID_TIPO_AVERIA),
    CONSTRAINT FIDE_TIPO_AVERIA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_TIPO_AVERIA_TB_ID_ESTADO_IDX ON FIDE_TIPO_AVERIA_TB(ID_ESTADO);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de tipos de medidor de agua
CREATE TABLE FIDE_TIPO_MEDIDOR_TB (
    ID_TIPO_MEDIDOR NUMBER CONSTRAINT FIDE_TIPO_MEDIDOR_TB_ID_TIPO_MEDIDOR_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_TIPO_MEDIDOR_TB_NOMBRE_NN NOT NULL,
    DESCRIPCION VARCHAR2(255),
    ID_ESTADO NUMBER CONSTRAINT FIDE_TIPO_MEDIDOR_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_TIPO_MEDIDOR_TB_ID_TIPO_MEDIDOR_PK PRIMARY KEY (ID_TIPO_MEDIDOR),
    CONSTRAINT FIDE_TIPO_MEDIDOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_TIPO_MEDIDOR_TB_ID_ESTADO_IDX ON FIDE_TIPO_MEDIDOR_TB(ID_ESTADO);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de tipos de orden de trabajo
CREATE TABLE FIDE_TIPO_ORDEN_TRABAJO_TB (
    ID_TIPO_ORDEN_TRABAJO NUMBER CONSTRAINT FIDE_TIPO_ORDEN_TRABAJO_TB_ID_TIPO_ORDEN_TRABAJO_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_TIPO_ORDEN_TRABAJO_TB_NOMBRE_NN NOT NULL,
    DESCRIPCION VARCHAR2(255),
    ID_ESTADO NUMBER CONSTRAINT FIDE_TIPO_ORDEN_TRABAJO_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_TIPO_ORDEN_TRABAJO_TB_ID_TIPO_ORDEN_TRABAJO_PK PRIMARY KEY (ID_TIPO_ORDEN_TRABAJO),
    CONSTRAINT FIDE_TIPO_ORDEN_TRABAJO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_TIPO_ORDEN_TRABAJO_TB_ID_ESTADO_IDX ON FIDE_TIPO_ORDEN_TRABAJO_TB(ID_ESTADO);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de unidades de medida para el inventario
CREATE TABLE FIDE_UNIDAD_MEDIDA_TB (
    ID_UNIDAD_MEDIDA NUMBER CONSTRAINT FIDE_UNIDAD_MEDIDA_TB_ID_UNIDAD_MEDIDA_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_UNIDAD_MEDIDA_TB_NOMBRE_NN NOT NULL,
    ABREVIATURA VARCHAR2(20),
    DESCRIPCION VARCHAR2(255),
    ID_ESTADO NUMBER CONSTRAINT FIDE_UNIDAD_MEDIDA_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_UNIDAD_MEDIDA_TB_ID_UNIDAD_MEDIDA_PK PRIMARY KEY (ID_UNIDAD_MEDIDA),
    CONSTRAINT FIDE_UNIDAD_MEDIDA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_UNIDAD_MEDIDA_TB_ID_ESTADO_IDX ON FIDE_UNIDAD_MEDIDA_TB(ID_ESTADO);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de tarifas de cobro por consumo de agua
CREATE TABLE FIDE_TARIFA_TB (
    ID_TARIFA NUMBER CONSTRAINT FIDE_TARIFA_TB_ID_TARIFA_NN NOT NULL,
    NOMBRE_TARIFA VARCHAR2(100) CONSTRAINT FIDE_TARIFA_TB_NOMBRE_TARIFA_NN NOT NULL,
    DESCRIPCION VARCHAR2(255),
    MONTO_BASE NUMBER(12,2),
    PRECIO_M3 NUMBER(12,4),
    CONSUMO_MINIMO_M3 NUMBER(12,4),
    CONSUMO_MAXIMO_M3 NUMBER(12,4),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ID_ESTADO NUMBER CONSTRAINT FIDE_TARIFA_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_TARIFA_TB_ID_TARIFA_PK PRIMARY KEY (ID_TARIFA),
    CONSTRAINT FIDE_TARIFA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_TARIFA_TB_ID_ESTADO_IDX ON FIDE_TARIFA_TB(ID_ESTADO);
/
CREATE INDEX FIDE_TARIFA_TB_FECHAS_IDX ON FIDE_TARIFA_TB(FECHA_INICIO, FECHA_FIN);
/


-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de países para abonados
CREATE TABLE FIDE_PAIS_ABONADO_TB (
    ID_PAIS NUMBER CONSTRAINT FIDE_PAIS_ABONADO_TB_ID_PAIS_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_PAIS_ABONADO_TB_NOMBRE_NN NOT NULL,
    CONSTRAINT FIDE_PAIS_ABONADO_TB_ID_PAIS_PK PRIMARY KEY (ID_PAIS)
);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de provincias para abonados
CREATE TABLE FIDE_PROVINCIA_ABONADO_TB (
    ID_PROVINCIA NUMBER CONSTRAINT FIDE_PROVINCIA_ABONADO_TB_ID_PROVINCIA_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_PROVINCIA_ABONADO_TB_NOMBRE_NN NOT NULL,
    CONSTRAINT FIDE_PROVINCIA_ABONADO_TB_ID_PROVINCIA_PK PRIMARY KEY (ID_PROVINCIA)
);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de cantones para abonados
CREATE TABLE FIDE_CANTON_ABONADO_TB (
    ID_CANTON NUMBER CONSTRAINT FIDE_CANTON_ABONADO_TB_ID_CANTON_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_CANTON_ABONADO_TB_NOMBRE_NN NOT NULL,
    CONSTRAINT FIDE_CANTON_ABONADO_TB_ID_CANTON_PK PRIMARY KEY (ID_CANTON)
);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de distritos para abonados
CREATE TABLE FIDE_DISTRITO_ABONADO_TB (
    ID_DISTRITO NUMBER CONSTRAINT FIDE_DISTRITO_ABONADO_TB_ID_DISTRITO_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_DISTRITO_ABONADO_TB_NOMBRE_NN NOT NULL,
    CONSTRAINT FIDE_DISTRITO_ABONADO_TB_ID_DISTRITO_PK PRIMARY KEY (ID_DISTRITO)
);
/


-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de países para empleados
CREATE TABLE FIDE_PAIS_EMPLEADO_TB (
    ID_PAIS NUMBER CONSTRAINT FIDE_PAIS_EMPLEADO_TB_ID_PAIS_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_PAIS_EMPLEADO_TB_NOMBRE_NN NOT NULL,
    CONSTRAINT FIDE_PAIS_EMPLEADO_TB_ID_PAIS_PK PRIMARY KEY (ID_PAIS)
);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de provincias para empleados
CREATE TABLE FIDE_PROVINCIA_EMPLEADO_TB (
    ID_PROVINCIA NUMBER CONSTRAINT FIDE_PROVINCIA_EMPLEADO_TB_ID_PROVINCIA_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_PROVINCIA_EMPLEADO_TB_NOMBRE_NN NOT NULL,
    CONSTRAINT FIDE_PROVINCIA_EMPLEADO_TB_ID_PROVINCIA_PK PRIMARY KEY (ID_PROVINCIA)
);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de cantones para empleados
CREATE TABLE FIDE_CANTON_EMPLEADO_TB (
    ID_CANTON NUMBER CONSTRAINT FIDE_CANTON_EMPLEADO_TB_ID_CANTON_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_CANTON_EMPLEADO_TB_NOMBRE_NN NOT NULL,
    CONSTRAINT FIDE_CANTON_EMPLEADO_TB_ID_CANTON_PK PRIMARY KEY (ID_CANTON)
);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de distritos para empleados
CREATE TABLE FIDE_DISTRITO_EMPLEADO_TB (
    ID_DISTRITO NUMBER CONSTRAINT FIDE_DISTRITO_EMPLEADO_TB_ID_DISTRITO_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_DISTRITO_EMPLEADO_TB_NOMBRE_NN NOT NULL,
    CONSTRAINT FIDE_DISTRITO_EMPLEADO_TB_ID_DISTRITO_PK PRIMARY KEY (ID_DISTRITO)
);
/



-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de países para proveedores
CREATE TABLE FIDE_PAIS_PROVEEDOR_TB (
    ID_PAIS NUMBER CONSTRAINT FIDE_PAIS_PROVEEDOR_TB_ID_PAIS_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_PAIS_PROVEEDOR_TB_NOMBRE_NN NOT NULL,
    CONSTRAINT FIDE_PAIS_PROVEEDOR_TB_ID_PAIS_PK PRIMARY KEY (ID_PAIS)
);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de provincias para proveedores
CREATE TABLE FIDE_PROVINCIA_PROVEEDOR_TB (
    ID_PROVINCIA NUMBER CONSTRAINT FIDE_PROVINCIA_PROVEEDOR_TB_ID_PROVINCIA_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_PROVINCIA_PROVEEDOR_TB_NOMBRE_NN NOT NULL,
    CONSTRAINT FIDE_PROVINCIA_PROVEEDOR_TB_ID_PROVINCIA_PK PRIMARY KEY (ID_PROVINCIA)
);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de cantones para proveedores
CREATE TABLE FIDE_CANTON_PROVEEDOR_TB (
    ID_CANTON NUMBER CONSTRAINT FIDE_CANTON_PROVEEDOR_TB_ID_CANTON_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_CANTON_PROVEEDOR_TB_NOMBRE_NN NOT NULL,
    CONSTRAINT FIDE_CANTON_PROVEEDOR_TB_ID_CANTON_PK PRIMARY KEY (ID_CANTON)
);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de distritos para proveedores
CREATE TABLE FIDE_DISTRITO_PROVEEDOR_TB (
    ID_DISTRITO NUMBER CONSTRAINT FIDE_DISTRITO_PROVEEDOR_TB_ID_DISTRITO_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_DISTRITO_PROVEEDOR_TB_NOMBRE_NN NOT NULL,
    CONSTRAINT FIDE_DISTRITO_PROVEEDOR_TB_ID_DISTRITO_PK PRIMARY KEY (ID_DISTRITO)
);
/


-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de abonados del servicio de agua
CREATE TABLE FIDE_ABONADO_TB (
    ID_ABONADO NUMBER CONSTRAINT FIDE_ABONADO_TB_ID_ABONADO_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_ABONADO_TB_NOMBRE_NN NOT NULL,
    APELLIDO_PATERNO VARCHAR2(100),
    APELLIDO_MATERNO VARCHAR2(100),
    ID_SECTOR NUMBER CONSTRAINT FIDE_ABONADO_TB_ID_SECTOR_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_ABONADO_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_ABONADO_TB_ID_ABONADO_PK PRIMARY KEY (ID_ABONADO),
    CONSTRAINT FIDE_ABONADO_TB_ID_SECTOR_FK FOREIGN KEY (ID_SECTOR) REFERENCES FIDE_SECTOR_TB(ID_SECTOR),
    CONSTRAINT FIDE_ABONADO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_ABONADO_TB_ID_SECTOR_IDX ON FIDE_ABONADO_TB(ID_SECTOR);
/
CREATE INDEX FIDE_ABONADO_TB_ID_ESTADO_IDX ON FIDE_ABONADO_TB(ID_ESTADO);
/
CREATE INDEX FIDE_ABONADO_TB_NOMBRE_IDX ON FIDE_ABONADO_TB(APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de empleados de la organización
CREATE TABLE FIDE_EMPLEADO_TB (
    ID_EMPLEADO NUMBER CONSTRAINT FIDE_EMPLEADO_TB_ID_EMPLEADO_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_EMPLEADO_TB_NOMBRE_NN NOT NULL,
    APELLIDO_PATERNO VARCHAR2(100),
    APELLIDO_MATERNO VARCHAR2(100),
    ID_PUESTO NUMBER CONSTRAINT FIDE_EMPLEADO_TB_ID_PUESTO_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_EMPLEADO_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_EMPLEADO_TB_ID_EMPLEADO_PK PRIMARY KEY (ID_EMPLEADO),
    CONSTRAINT FIDE_EMPLEADO_TB_ID_PUESTO_FK FOREIGN KEY (ID_PUESTO) REFERENCES FIDE_PUESTO_TB(ID_PUESTO),
    CONSTRAINT FIDE_EMPLEADO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_EMPLEADO_TB_ID_PUESTO_IDX ON FIDE_EMPLEADO_TB(ID_PUESTO);
/
CREATE INDEX FIDE_EMPLEADO_TB_ID_ESTADO_IDX ON FIDE_EMPLEADO_TB(ID_ESTADO);
/
CREATE INDEX FIDE_EMPLEADO_TB_NOMBRE_IDX ON FIDE_EMPLEADO_TB(APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de proveedores de materiales y servicios
CREATE TABLE FIDE_PROVEEDOR_TB (
    ID_PROVEEDOR NUMBER CONSTRAINT FIDE_PROVEEDOR_TB_ID_PROVEEDOR_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_PROVEEDOR_TB_NOMBRE_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_PROVEEDOR_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_PROVEEDOR_TB_ID_PROVEEDOR_PK PRIMARY KEY (ID_PROVEEDOR),
    CONSTRAINT FIDE_PROVEEDOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_PROVEEDOR_TB_ID_ESTADO_IDX ON FIDE_PROVEEDOR_TB(ID_ESTADO);
/
CREATE INDEX FIDE_PROVEEDOR_TB_NOMBRE_IDX ON FIDE_PROVEEDOR_TB(NOMBRE);
/


-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de correos electrónicos de abonados
CREATE TABLE FIDE_CORREO_ABONADO_TB (
    ID_ABONADO NUMBER CONSTRAINT FIDE_CORREO_ABONADO_TB_ID_ABONADO_NN NOT NULL,
    CORREO VARCHAR2(150) CONSTRAINT FIDE_CORREO_ABONADO_TB_CORREO_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_CORREO_ABONADO_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_CORREO_ABONADO_TB_PK PRIMARY KEY (ID_ABONADO, CORREO),
    CONSTRAINT FIDE_CORREO_ABONADO_TB_ID_ABONADO_FK FOREIGN KEY (ID_ABONADO) REFERENCES FIDE_ABONADO_TB(ID_ABONADO),
    CONSTRAINT FIDE_CORREO_ABONADO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_CORREO_ABONADO_TB_ID_ESTADO_IDX ON FIDE_CORREO_ABONADO_TB(ID_ESTADO);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de correos electrónicos de empleados
CREATE TABLE FIDE_CORREO_EMPLEADO_TB (
    ID_EMPLEADO NUMBER CONSTRAINT FIDE_CORREO_EMPLEADO_TB_ID_EMPLEADO_NN NOT NULL,
    CORREO VARCHAR2(150) CONSTRAINT FIDE_CORREO_EMPLEADO_TB_CORREO_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_CORREO_EMPLEADO_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_CORREO_EMPLEADO_TB_PK PRIMARY KEY (ID_EMPLEADO, CORREO),
    CONSTRAINT FIDE_CORREO_EMPLEADO_TB_ID_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES FIDE_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FIDE_CORREO_EMPLEADO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_CORREO_EMPLEADO_TB_ID_ESTADO_IDX ON FIDE_CORREO_EMPLEADO_TB(ID_ESTADO);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de correos electrónicos de proveedores
CREATE TABLE FIDE_CORREO_PROVEEDOR_TB (
    ID_PROVEEDOR NUMBER CONSTRAINT FIDE_CORREO_PROVEEDOR_TB_ID_PROVEEDOR_NN NOT NULL,
    CORREO VARCHAR2(150) CONSTRAINT FIDE_CORREO_PROVEEDOR_TB_CORREO_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_CORREO_PROVEEDOR_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_CORREO_PROVEEDOR_TB_PK PRIMARY KEY (ID_PROVEEDOR, CORREO),
    CONSTRAINT FIDE_CORREO_PROVEEDOR_TB_ID_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES FIDE_PROVEEDOR_TB(ID_PROVEEDOR),
    CONSTRAINT FIDE_CORREO_PROVEEDOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_CORREO_PROVEEDOR_TB_ID_ESTADO_IDX ON FIDE_CORREO_PROVEEDOR_TB(ID_ESTADO);
/


-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de teléfonos de abonados
CREATE TABLE FIDE_TELEFONO_ABONADO_TB (
    ID_ABONADO NUMBER CONSTRAINT FIDE_TELEFONO_ABONADO_TB_ID_ABONADO_NN NOT NULL,
    NUMERO VARCHAR2(30) CONSTRAINT FIDE_TELEFONO_ABONADO_TB_NUMERO_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_TELEFONO_ABONADO_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_TELEFONO_ABONADO_TB_PK PRIMARY KEY (ID_ABONADO, NUMERO),
    CONSTRAINT FIDE_TELEFONO_ABONADO_TB_ID_ABONADO_FK FOREIGN KEY (ID_ABONADO) REFERENCES FIDE_ABONADO_TB(ID_ABONADO),
    CONSTRAINT FIDE_TELEFONO_ABONADO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_TELEFONO_ABONADO_TB_ID_ESTADO_IDX ON FIDE_TELEFONO_ABONADO_TB(ID_ESTADO);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de teléfonos de empleados
CREATE TABLE FIDE_TELEFONO_EMPLEADO_TB (
    ID_EMPLEADO NUMBER CONSTRAINT FIDE_TELEFONO_EMPLEADO_TB_ID_EMPLEADO_NN NOT NULL,
    NUMERO VARCHAR2(30) CONSTRAINT FIDE_TELEFONO_EMPLEADO_TB_NUMERO_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_TELEFONO_EMPLEADO_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_TELEFONO_EMPLEADO_TB_PK PRIMARY KEY (ID_EMPLEADO, NUMERO),
    CONSTRAINT FIDE_TELEFONO_EMPLEADO_TB_ID_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES FIDE_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FIDE_TELEFONO_EMPLEADO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_TELEFONO_EMPLEADO_TB_ID_ESTADO_IDX ON FIDE_TELEFONO_EMPLEADO_TB(ID_ESTADO);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de teléfonos de proveedores
CREATE TABLE FIDE_TELEFONO_PROVEEDOR_TB (
    ID_PROVEEDOR NUMBER CONSTRAINT FIDE_TELEFONO_PROVEEDOR_TB_ID_PROVEEDOR_NN NOT NULL,
    NUMERO VARCHAR2(30) CONSTRAINT FIDE_TELEFONO_PROVEEDOR_TB_NUMERO_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_TELEFONO_PROVEEDOR_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_TELEFONO_PROVEEDOR_TB_PK PRIMARY KEY (ID_PROVEEDOR, NUMERO),
    CONSTRAINT FIDE_TELEFONO_PROVEEDOR_TB_ID_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES FIDE_PROVEEDOR_TB(ID_PROVEEDOR),
    CONSTRAINT FIDE_TELEFONO_PROVEEDOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_TELEFONO_PROVEEDOR_TB_ID_ESTADO_IDX ON FIDE_TELEFONO_PROVEEDOR_TB(ID_ESTADO);
/


-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de direcciones de abonados
CREATE TABLE FIDE_DIRECCIONES_ABONADO_TB (
    ID_ABONADO NUMBER CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_ID_ABONADO_NN NOT NULL,
    ID_PAIS NUMBER CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_ID_PAIS_NN NOT NULL,
    ID_PROVINCIA NUMBER CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_ID_PROVINCIA_NN NOT NULL,
    ID_CANTON NUMBER CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_ID_CANTON_NN NOT NULL,
    ID_DISTRITO NUMBER CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_ID_DISTRITO_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_PK PRIMARY KEY (ID_ABONADO, ID_PAIS, ID_PROVINCIA, ID_CANTON, ID_DISTRITO),
    CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_ID_ABONADO_FK FOREIGN KEY (ID_ABONADO) REFERENCES FIDE_ABONADO_TB(ID_ABONADO),
    CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_ID_PAIS_FK FOREIGN KEY (ID_PAIS) REFERENCES FIDE_PAIS_ABONADO_TB(ID_PAIS),
    CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_ID_PROVINCIA_FK FOREIGN KEY (ID_PROVINCIA) REFERENCES FIDE_PROVINCIA_ABONADO_TB(ID_PROVINCIA),
    CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_ID_CANTON_FK FOREIGN KEY (ID_CANTON) REFERENCES FIDE_CANTON_ABONADO_TB(ID_CANTON),
    CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_ID_DISTRITO_FK FOREIGN KEY (ID_DISTRITO) REFERENCES FIDE_DISTRITO_ABONADO_TB(ID_DISTRITO),
    CONSTRAINT FIDE_DIRECCIONES_ABONADO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_DIRECCIONES_ABONADO_TB_ID_ESTADO_IDX ON FIDE_DIRECCIONES_ABONADO_TB(ID_ESTADO);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de direcciones de empleados
CREATE TABLE FIDE_DIRECCIONES_EMPLEADO_TB (
    ID_EMPLEADO NUMBER CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_ID_EMPLEADO_NN NOT NULL,
    ID_PAIS NUMBER CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_ID_PAIS_NN NOT NULL,
    ID_PROVINCIA NUMBER CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_ID_PROVINCIA_NN NOT NULL,
    ID_CANTON NUMBER CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_ID_CANTON_NN NOT NULL,
    ID_DISTRITO NUMBER CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_ID_DISTRITO_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_PK PRIMARY KEY (ID_EMPLEADO, ID_PAIS, ID_PROVINCIA, ID_CANTON, ID_DISTRITO),
    CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_ID_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES FIDE_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_ID_PAIS_FK FOREIGN KEY (ID_PAIS) REFERENCES FIDE_PAIS_EMPLEADO_TB(ID_PAIS),
    CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_ID_PROVINCIA_FK FOREIGN KEY (ID_PROVINCIA) REFERENCES FIDE_PROVINCIA_EMPLEADO_TB(ID_PROVINCIA),
    CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_ID_CANTON_FK FOREIGN KEY (ID_CANTON) REFERENCES FIDE_CANTON_EMPLEADO_TB(ID_CANTON),
    CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_ID_DISTRITO_FK FOREIGN KEY (ID_DISTRITO) REFERENCES FIDE_DISTRITO_EMPLEADO_TB(ID_DISTRITO),
    CONSTRAINT FIDE_DIRECCIONES_EMPLEADO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_DIRECCIONES_EMPLEADO_TB_ID_ESTADO_IDX ON FIDE_DIRECCIONES_EMPLEADO_TB(ID_ESTADO);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de direcciones de proveedores
CREATE TABLE FIDE_DIRECCIONES_PROVEEDOR_TB (
    ID_PROVEEDOR NUMBER CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_ID_PROVEEDOR_NN NOT NULL,
    ID_PAIS NUMBER CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_ID_PAIS_NN NOT NULL,
    ID_PROVINCIA NUMBER CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_ID_PROVINCIA_NN NOT NULL,
    ID_CANTON NUMBER CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_ID_CANTON_NN NOT NULL,
    ID_DISTRITO NUMBER CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_ID_DISTRITO_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_PK PRIMARY KEY (ID_PROVEEDOR, ID_PAIS, ID_PROVINCIA, ID_CANTON, ID_DISTRITO),
    CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_ID_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES FIDE_PROVEEDOR_TB(ID_PROVEEDOR),
    CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_ID_PAIS_FK FOREIGN KEY (ID_PAIS) REFERENCES FIDE_PAIS_PROVEEDOR_TB(ID_PAIS),
    CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_ID_PROVINCIA_FK FOREIGN KEY (ID_PROVINCIA) REFERENCES FIDE_PROVINCIA_PROVEEDOR_TB(ID_PROVINCIA),
    CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_ID_CANTON_FK FOREIGN KEY (ID_CANTON) REFERENCES FIDE_CANTON_PROVEEDOR_TB(ID_CANTON),
    CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_ID_DISTRITO_FK FOREIGN KEY (ID_DISTRITO) REFERENCES FIDE_DISTRITO_PROVEEDOR_TB(ID_DISTRITO),
    CONSTRAINT FIDE_DIRECCIONES_PROVEEDOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_DIRECCIONES_PROVEEDOR_TB_ID_ESTADO_IDX ON FIDE_DIRECCIONES_PROVEEDOR_TB(ID_ESTADO);
/


-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de medidores de agua instalados en los abonados
CREATE TABLE FIDE_MEDIDOR_TB (
    ID_MEDIDOR NUMBER CONSTRAINT FIDE_MEDIDOR_TB_ID_MEDIDOR_NN NOT NULL,
    NUMERO_MEDIDOR VARCHAR2(50) CONSTRAINT FIDE_MEDIDOR_TB_NUMERO_MEDIDOR_NN NOT NULL,
    FECHA_INSTALACION DATE,
    MARCA VARCHAR2(100),
    ID_TIPO_MEDIDOR NUMBER CONSTRAINT FIDE_MEDIDOR_TB_ID_TIPO_MEDIDOR_NN NOT NULL,
    ID_ABONADO NUMBER CONSTRAINT FIDE_MEDIDOR_TB_ID_ABONADO_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_MEDIDOR_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_MEDIDOR_TB_ID_MEDIDOR_PK PRIMARY KEY (ID_MEDIDOR),
    CONSTRAINT FIDE_MEDIDOR_TB_ID_TIPO_MEDIDOR_FK FOREIGN KEY (ID_TIPO_MEDIDOR) REFERENCES FIDE_TIPO_MEDIDOR_TB(ID_TIPO_MEDIDOR),
    CONSTRAINT FIDE_MEDIDOR_TB_ID_ABONADO_FK FOREIGN KEY (ID_ABONADO) REFERENCES FIDE_ABONADO_TB(ID_ABONADO),
    CONSTRAINT FIDE_MEDIDOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_MEDIDOR_TB_ID_TIPO_MEDIDOR_IDX ON FIDE_MEDIDOR_TB(ID_TIPO_MEDIDOR);
/
CREATE INDEX FIDE_MEDIDOR_TB_ID_ABONADO_IDX ON FIDE_MEDIDOR_TB(ID_ABONADO);
/
CREATE INDEX FIDE_MEDIDOR_TB_ID_ESTADO_IDX ON FIDE_MEDIDOR_TB(ID_ESTADO);
/
CREATE INDEX FIDE_MEDIDOR_TB_NUMERO_IDX ON FIDE_MEDIDOR_TB(NUMERO_MEDIDOR);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de lecturas de consumo registradas por los empleados
CREATE TABLE FIDE_LECTURA_TB (
    ID_LECTURA NUMBER CONSTRAINT FIDE_LECTURA_TB_ID_LECTURA_NN NOT NULL,
    FECHA_LECTURA DATE CONSTRAINT FIDE_LECTURA_TB_FECHA_LECTURA_NN NOT NULL,
    LECTURA_ANTERIOR NUMBER(12,4),
    LECTURA_ACTUAL NUMBER(12,4) CONSTRAINT FIDE_LECTURA_TB_LECTURA_ACTUAL_NN NOT NULL,
    CONSUMO_M3 NUMBER(12,4),
    ID_MEDIDOR NUMBER CONSTRAINT FIDE_LECTURA_TB_ID_MEDIDOR_NN NOT NULL,
    ID_EMPLEADO NUMBER CONSTRAINT FIDE_LECTURA_TB_ID_EMPLEADO_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_LECTURA_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_LECTURA_TB_ID_LECTURA_PK PRIMARY KEY (ID_LECTURA),
    CONSTRAINT FIDE_LECTURA_TB_ID_MEDIDOR_FK FOREIGN KEY (ID_MEDIDOR) REFERENCES FIDE_MEDIDOR_TB(ID_MEDIDOR),
    CONSTRAINT FIDE_LECTURA_TB_ID_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES FIDE_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FIDE_LECTURA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_LECTURA_TB_ID_MEDIDOR_IDX ON FIDE_LECTURA_TB(ID_MEDIDOR);
/
CREATE INDEX FIDE_LECTURA_TB_ID_EMPLEADO_IDX ON FIDE_LECTURA_TB(ID_EMPLEADO);
/
CREATE INDEX FIDE_LECTURA_TB_ID_ESTADO_IDX ON FIDE_LECTURA_TB(ID_ESTADO);
/
CREATE INDEX FIDE_LECTURA_TB_FECHA_IDX ON FIDE_LECTURA_TB(FECHA_LECTURA);
/



-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de facturas emitidas a los abonados
CREATE TABLE FIDE_FACTURA_TB (
    ID_FACTURA NUMBER CONSTRAINT FIDE_FACTURA_TB_ID_FACTURA_NN NOT NULL,
    NUMERO_FACTURA VARCHAR2(50) CONSTRAINT FIDE_FACTURA_TB_NUMERO_FACTURA_NN NOT NULL,
    FECHA_FACTURA DATE CONSTRAINT FIDE_FACTURA_TB_FECHA_FACTURA_NN NOT NULL,
    FECHA_VENCIMIENTO DATE,
    SUBTOTAL NUMBER(12,2),
    IMPUESTOS NUMBER(12,2),
    TOTAL NUMBER(12,2),
    ID_ABONADO NUMBER CONSTRAINT FIDE_FACTURA_TB_ID_ABONADO_NN NOT NULL,
    ID_LECTURA NUMBER CONSTRAINT FIDE_FACTURA_TB_ID_LECTURA_NN NOT NULL,
    ID_TARIFA NUMBER CONSTRAINT FIDE_FACTURA_TB_ID_TARIFA_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_FACTURA_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_FACTURA_TB_ID_FACTURA_PK PRIMARY KEY (ID_FACTURA),
    CONSTRAINT FIDE_FACTURA_TB_ID_ABONADO_FK FOREIGN KEY (ID_ABONADO) REFERENCES FIDE_ABONADO_TB(ID_ABONADO),
    CONSTRAINT FIDE_FACTURA_TB_ID_LECTURA_FK FOREIGN KEY (ID_LECTURA) REFERENCES FIDE_LECTURA_TB(ID_LECTURA),
    CONSTRAINT FIDE_FACTURA_TB_ID_TARIFA_FK FOREIGN KEY (ID_TARIFA) REFERENCES FIDE_TARIFA_TB(ID_TARIFA),
    CONSTRAINT FIDE_FACTURA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_FACTURA_TB_ID_ABONADO_IDX ON FIDE_FACTURA_TB(ID_ABONADO);
/
CREATE INDEX FIDE_FACTURA_TB_ID_LECTURA_IDX ON FIDE_FACTURA_TB(ID_LECTURA);
/
CREATE INDEX FIDE_FACTURA_TB_ID_TARIFA_IDX ON FIDE_FACTURA_TB(ID_TARIFA);
/
CREATE INDEX FIDE_FACTURA_TB_ID_ESTADO_IDX ON FIDE_FACTURA_TB(ID_ESTADO);
/
CREATE INDEX FIDE_FACTURA_TB_NUMERO_IDX ON FIDE_FACTURA_TB(NUMERO_FACTURA);
/
CREATE INDEX FIDE_FACTURA_TB_FECHA_IDX ON FIDE_FACTURA_TB(FECHA_FACTURA);
/
CREATE INDEX FIDE_FACTURA_TB_VENCIMIENTO_IDX ON FIDE_FACTURA_TB(FECHA_VENCIMIENTO);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de líneas de detalle de cada factura de abonado
CREATE TABLE FIDE_DETALLE_FACTURA_TB (
    ID_DETALLE_FACTURA NUMBER CONSTRAINT FIDE_DETALLE_FACTURA_TB_ID_DETALLE_FACTURA_NN NOT NULL,
    CONCEPTO VARCHAR2(255) CONSTRAINT FIDE_DETALLE_FACTURA_TB_CONCEPTO_NN NOT NULL,
    CANTIDAD NUMBER(12,4),
    PRECIO_UNITARIO NUMBER(12,4),
    SUBTOTAL NUMBER(12,2),
    ID_FACTURA NUMBER CONSTRAINT FIDE_DETALLE_FACTURA_TB_ID_FACTURA_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_DETALLE_FACTURA_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_DETALLE_FACTURA_TB_ID_DETALLE_FACTURA_PK PRIMARY KEY (ID_DETALLE_FACTURA),
    CONSTRAINT FIDE_DETALLE_FACTURA_TB_ID_FACTURA_FK FOREIGN KEY (ID_FACTURA) REFERENCES FIDE_FACTURA_TB(ID_FACTURA),
    CONSTRAINT FIDE_DETALLE_FACTURA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_DETALLE_FACTURA_TB_ID_FACTURA_IDX ON FIDE_DETALLE_FACTURA_TB(ID_FACTURA);
/
CREATE INDEX FIDE_DETALLE_FACTURA_TB_ID_ESTADO_IDX ON FIDE_DETALLE_FACTURA_TB(ID_ESTADO);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de pagos realizados por los abonados
CREATE TABLE FIDE_PAGO_TB (
    ID_PAGO NUMBER CONSTRAINT FIDE_PAGO_TB_ID_PAGO_NN NOT NULL,
    MONTO NUMBER(12,2) CONSTRAINT FIDE_PAGO_TB_MONTO_NN NOT NULL,
    FECHA_PAGO DATE CONSTRAINT FIDE_PAGO_TB_FECHA_PAGO_NN NOT NULL,
    REFERENCIA VARCHAR2(100),
    ID_FACTURA NUMBER CONSTRAINT FIDE_PAGO_TB_ID_FACTURA_NN NOT NULL,
    ID_METODO_PAGO NUMBER CONSTRAINT FIDE_PAGO_TB_ID_METODO_PAGO_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_PAGO_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_PAGO_TB_ID_PAGO_PK PRIMARY KEY (ID_PAGO),
    CONSTRAINT FIDE_PAGO_TB_ID_FACTURA_FK FOREIGN KEY (ID_FACTURA) REFERENCES FIDE_FACTURA_TB(ID_FACTURA),
    CONSTRAINT FIDE_PAGO_TB_ID_METODO_PAGO_FK FOREIGN KEY (ID_METODO_PAGO) REFERENCES FIDE_METODO_PAGO_TB(ID_METODO_PAGO),
    CONSTRAINT FIDE_PAGO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_PAGO_TB_ID_FACTURA_IDX ON FIDE_PAGO_TB(ID_FACTURA);
/
CREATE INDEX FIDE_PAGO_TB_ID_METODO_PAGO_IDX ON FIDE_PAGO_TB(ID_METODO_PAGO);
/
CREATE INDEX FIDE_PAGO_TB_ID_ESTADO_IDX ON FIDE_PAGO_TB(ID_ESTADO);
/
CREATE INDEX FIDE_PAGO_TB_FECHA_IDX ON FIDE_PAGO_TB(FECHA_PAGO);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de artículos del inventario
CREATE TABLE FIDE_INVENTARIO_TB (
    ID_INVENTARIO NUMBER CONSTRAINT FIDE_INVENTARIO_TB_ID_INVENTARIO_NN NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_INVENTARIO_TB_NOMBRE_NN NOT NULL,
    DESCRIPCION VARCHAR2(255),
    ID_UNIDAD_MEDIDA NUMBER CONSTRAINT FIDE_INVENTARIO_TB_ID_UNIDAD_MEDIDA_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_INVENTARIO_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_INVENTARIO_TB_ID_INVENTARIO_PK PRIMARY KEY (ID_INVENTARIO),
    CONSTRAINT FIDE_INVENTARIO_TB_ID_UNIDAD_MEDIDA_FK FOREIGN KEY (ID_UNIDAD_MEDIDA) REFERENCES FIDE_UNIDAD_MEDIDA_TB(ID_UNIDAD_MEDIDA),
    CONSTRAINT FIDE_INVENTARIO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_INVENTARIO_TB_ID_UNIDAD_MEDIDA_IDX ON FIDE_INVENTARIO_TB(ID_UNIDAD_MEDIDA);
/
CREATE INDEX FIDE_INVENTARIO_TB_ID_ESTADO_IDX ON FIDE_INVENTARIO_TB(ID_ESTADO);
/
CREATE INDEX FIDE_INVENTARIO_TB_NOMBRE_IDX ON FIDE_INVENTARIO_TB(NOMBRE);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de stock en almacén por artículo de inventario
CREATE TABLE FIDE_ALMACEN_INVENTARIO_TB (
    ID_ALMACEN_INVENTARIO NUMBER CONSTRAINT FIDE_ALMACEN_INVENTARIO_TB_ID_ALMACEN_INVENTARIO_NN NOT NULL,
    STOCK_ACTUAL NUMBER(12,4),
    STOCK_MIN NUMBER(12,4),
    ID_INVENTARIO NUMBER CONSTRAINT FIDE_ALMACEN_INVENTARIO_TB_ID_INVENTARIO_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_ALMACEN_INVENTARIO_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_ALMACEN_INVENTARIO_TB_ID_ALMACEN_INVENTARIO_PK PRIMARY KEY (ID_ALMACEN_INVENTARIO),
    CONSTRAINT FIDE_ALMACEN_INVENTARIO_TB_ID_INVENTARIO_FK FOREIGN KEY (ID_INVENTARIO) REFERENCES FIDE_INVENTARIO_TB(ID_INVENTARIO),
    CONSTRAINT FIDE_ALMACEN_INVENTARIO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_ALMACEN_INVENTARIO_TB_ID_INVENTARIO_IDX ON FIDE_ALMACEN_INVENTARIO_TB(ID_INVENTARIO);
/
CREATE INDEX FIDE_ALMACEN_INVENTARIO_TB_ID_ESTADO_IDX ON FIDE_ALMACEN_INVENTARIO_TB(ID_ESTADO);
/
CREATE INDEX FIDE_ALMACEN_INVENTARIO_TB_STOCK_IDX ON FIDE_ALMACEN_INVENTARIO_TB(STOCK_ACTUAL, STOCK_MIN);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla puente entre proveedores y artículos de inventario
CREATE TABLE FIDE_PROVEEDOR_INVENTARIO_TB (
    ID_PROVEEDOR NUMBER CONSTRAINT FIDE_PROVEEDOR_INVENTARIO_TB_ID_PROVEEDOR_NN NOT NULL,
    ID_INVENTARIO NUMBER CONSTRAINT FIDE_PROVEEDOR_INVENTARIO_TB_ID_INVENTARIO_NN NOT NULL,
    CONSTRAINT FIDE_PROVEEDOR_INVENTARIO_TB_PK PRIMARY KEY (ID_PROVEEDOR, ID_INVENTARIO),
    CONSTRAINT FIDE_PROVEEDOR_INVENTARIO_TB_ID_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES FIDE_PROVEEDOR_TB(ID_PROVEEDOR),
    CONSTRAINT FIDE_PROVEEDOR_INVENTARIO_TB_ID_INVENTARIO_FK FOREIGN KEY (ID_INVENTARIO) REFERENCES FIDE_INVENTARIO_TB(ID_INVENTARIO)
);
/
CREATE INDEX FIDE_PROVEEDOR_INVENTARIO_TB_ID_INVENTARIO_IDX ON FIDE_PROVEEDOR_INVENTARIO_TB(ID_INVENTARIO);
/
CREATE INDEX FIDE_PROVEEDOR_INVENTARIO_TB_ID_PROVEEDOR_IDX ON FIDE_PROVEEDOR_INVENTARIO_TB(ID_PROVEEDOR);
/



-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de facturas recibidas de proveedores
CREATE TABLE FIDE_FACTURA_PROVEEDOR_TB (
    ID_FACTURA_PROVEEDOR NUMBER CONSTRAINT FIDE_FACTURA_PROVEEDOR_TB_ID_FACTURA_PROVEEDOR_NN NOT NULL,
    NUMERO_FACTURA VARCHAR2(50) CONSTRAINT FIDE_FACTURA_PROVEEDOR_TB_NUMERO_FACTURA_NN NOT NULL,
    FECHA_FACTURA DATE CONSTRAINT FIDE_FACTURA_PROVEEDOR_TB_FECHA_FACTURA_NN NOT NULL,
    FECHA_VENCIMIENTO DATE,
    SUBTOTAL NUMBER(12,2),
    IMPUESTOS NUMBER(12,2),
    TOTAL NUMBER(12,2),
    ID_PROVEEDOR NUMBER CONSTRAINT FIDE_FACTURA_PROVEEDOR_TB_ID_PROVEEDOR_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_FACTURA_PROVEEDOR_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_FACTURA_PROVEEDOR_TB_ID_FACTURA_PROVEEDOR_PK PRIMARY KEY (ID_FACTURA_PROVEEDOR),
    CONSTRAINT FIDE_FACTURA_PROVEEDOR_TB_ID_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES FIDE_PROVEEDOR_TB(ID_PROVEEDOR),
    CONSTRAINT FIDE_FACTURA_PROVEEDOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_FACTURA_PROVEEDOR_TB_ID_PROVEEDOR_IDX ON FIDE_FACTURA_PROVEEDOR_TB(ID_PROVEEDOR);
/
CREATE INDEX FIDE_FACTURA_PROVEEDOR_TB_ID_ESTADO_IDX ON FIDE_FACTURA_PROVEEDOR_TB(ID_ESTADO);
/
CREATE INDEX FIDE_FACTURA_PROVEEDOR_TB_NUMERO_IDX ON FIDE_FACTURA_PROVEEDOR_TB(NUMERO_FACTURA);
/
CREATE INDEX FIDE_FACTURA_PROVEEDOR_TB_FECHA_IDX ON FIDE_FACTURA_PROVEEDOR_TB(FECHA_FACTURA);
/
CREATE INDEX FIDE_FACTURA_PROVEEDOR_TB_VENCIMIENTO_IDX ON FIDE_FACTURA_PROVEEDOR_TB(FECHA_VENCIMIENTO);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de líneas de detalle de cada factura de proveedor
CREATE TABLE FIDE_DETALLE_FACTURA_PROVEEDOR_TB (
    ID_DETALLE_FACTURA_PROVEEDOR NUMBER CONSTRAINT FIDE_DETALLE_FACTURA_PROVEEDOR_TB_ID_DETALLE_FACTURA_PROVEEDOR_NN NOT NULL,
    CONCEPTO VARCHAR2(255) CONSTRAINT FIDE_DETALLE_FACTURA_PROVEEDOR_TB_CONCEPTO_NN NOT NULL,
    CANTIDAD NUMBER(12,4),
    PRECIO_UNITARIO NUMBER(12,4),
    SUBTOTAL NUMBER(12,2),
    ID_FACTURA_PROVEEDOR NUMBER CONSTRAINT FIDE_DETALLE_FACTURA_PROVEEDOR_TB_ID_FACTURA_PROVEEDOR_NN NOT NULL,
    ID_INVENTARIO NUMBER CONSTRAINT FIDE_DETALLE_FACTURA_PROVEEDOR_TB_ID_INVENTARIO_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_DETALLE_FACTURA_PROVEEDOR_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_DETALLE_FACTURA_PROVEEDOR_TB_ID_DETALLE_FACTURA_PROVEEDOR_PK PRIMARY KEY (ID_DETALLE_FACTURA_PROVEEDOR),
    CONSTRAINT FIDE_DETALLE_FACTURA_PROVEEDOR_TB_ID_FACTURA_PROVEEDOR_FK FOREIGN KEY (ID_FACTURA_PROVEEDOR) REFERENCES FIDE_FACTURA_PROVEEDOR_TB(ID_FACTURA_PROVEEDOR),
    CONSTRAINT FIDE_DETALLE_FACTURA_PROVEEDOR_TB_ID_INVENTARIO_FK FOREIGN KEY (ID_INVENTARIO) REFERENCES FIDE_INVENTARIO_TB(ID_INVENTARIO),
    CONSTRAINT FIDE_DETALLE_FACTURA_PROVEEDOR_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_DETALLE_FACTURA_PROVEEDOR_TB_ID_FACTURA_PROVEEDOR_IDX ON FIDE_DETALLE_FACTURA_PROVEEDOR_TB(ID_FACTURA_PROVEEDOR);
/
CREATE INDEX FIDE_DETALLE_FACTURA_PROVEEDOR_TB_ID_INVENTARIO_IDX ON FIDE_DETALLE_FACTURA_PROVEEDOR_TB(ID_INVENTARIO);
/
CREATE INDEX FIDE_DETALLE_FACTURA_PROVEEDOR_TB_ID_ESTADO_IDX ON FIDE_DETALLE_FACTURA_PROVEEDOR_TB(ID_ESTADO);
/



-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de averías reportadas por los abonados
CREATE TABLE FIDE_AVERIA_TB (
    ID_AVERIA NUMBER CONSTRAINT FIDE_AVERIA_TB_ID_AVERIA_NN NOT NULL,
    FECHA_REPORTE DATE CONSTRAINT FIDE_AVERIA_TB_FECHA_REPORTE_NN NOT NULL,
    DESCRIPCION VARCHAR2(500),
    UBICACION_REFERENCIA VARCHAR2(255),
    ID_ABONADO NUMBER CONSTRAINT FIDE_AVERIA_TB_ID_ABONADO_NN NOT NULL,
    ID_SECTOR NUMBER CONSTRAINT FIDE_AVERIA_TB_ID_SECTOR_NN NOT NULL,
    ID_TIPO_AVERIA NUMBER CONSTRAINT FIDE_AVERIA_TB_ID_TIPO_AVERIA_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_AVERIA_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_AVERIA_TB_ID_AVERIA_PK PRIMARY KEY (ID_AVERIA),
    CONSTRAINT FIDE_AVERIA_TB_ID_ABONADO_FK FOREIGN KEY (ID_ABONADO) REFERENCES FIDE_ABONADO_TB(ID_ABONADO),
    CONSTRAINT FIDE_AVERIA_TB_ID_SECTOR_FK FOREIGN KEY (ID_SECTOR) REFERENCES FIDE_SECTOR_TB(ID_SECTOR),
    CONSTRAINT FIDE_AVERIA_TB_ID_TIPO_AVERIA_FK FOREIGN KEY (ID_TIPO_AVERIA) REFERENCES FIDE_TIPO_AVERIA_TB(ID_TIPO_AVERIA),
    CONSTRAINT FIDE_AVERIA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_AVERIA_TB_ID_ABONADO_IDX ON FIDE_AVERIA_TB(ID_ABONADO);
/
CREATE INDEX FIDE_AVERIA_TB_ID_SECTOR_IDX ON FIDE_AVERIA_TB(ID_SECTOR);
/
CREATE INDEX FIDE_AVERIA_TB_ID_TIPO_AVERIA_IDX ON FIDE_AVERIA_TB(ID_TIPO_AVERIA);
/
CREATE INDEX FIDE_AVERIA_TB_ID_ESTADO_IDX ON FIDE_AVERIA_TB(ID_ESTADO);
/
CREATE INDEX FIDE_AVERIA_TB_FECHA_IDX ON FIDE_AVERIA_TB(FECHA_REPORTE);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de órdenes de trabajo generadas para atender averías
CREATE TABLE FIDE_ORDEN_TRABAJO_TB (
    ID_ORDEN_TRABAJO NUMBER CONSTRAINT FIDE_ORDEN_TRABAJO_TB_ID_ORDEN_TRABAJO_NN NOT NULL,
    FECHA_ASIGNACION DATE,
    FECHA_CIERRE DATE,
    DESCRIPCION_TRABAJO VARCHAR2(500),
    OBSERVACIONES VARCHAR2(500),z
    ID_AVERIA NUMBER CONSTRAINT FIDE_ORDEN_TRABAJO_TB_ID_AVERIA_NN NOT NULL,
    ID_TIPO_ORDEN_TRABAJO NUMBER CONSTRAINT FIDE_ORDEN_TRABAJO_TB_ID_TIPO_ORDEN_TRABAJO_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_ORDEN_TRABAJO_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_ORDEN_TRABAJO_TB_ID_ORDEN_TRABAJO_PK PRIMARY KEY (ID_ORDEN_TRABAJO),
    CONSTRAINT FIDE_ORDEN_TRABAJO_TB_ID_AVERIA_FK FOREIGN KEY (ID_AVERIA) REFERENCES FIDE_AVERIA_TB(ID_AVERIA),
    CONSTRAINT FIDE_ORDEN_TRABAJO_TB_ID_TIPO_ORDEN_TRABAJO_FK FOREIGN KEY (ID_TIPO_ORDEN_TRABAJO) REFERENCES FIDE_TIPO_ORDEN_TRABAJO_TB(ID_TIPO_ORDEN_TRABAJO),
    CONSTRAINT FIDE_ORDEN_TRABAJO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_ORDEN_TRABAJO_TB_ID_AVERIA_IDX ON FIDE_ORDEN_TRABAJO_TB(ID_AVERIA);
/
CREATE INDEX FIDE_ORDEN_TRABAJO_TB_ID_TIPO_ORDEN_TRABAJO_IDX ON FIDE_ORDEN_TRABAJO_TB(ID_TIPO_ORDEN_TRABAJO);
/
CREATE INDEX FIDE_ORDEN_TRABAJO_TB_ID_ESTADO_IDX ON FIDE_ORDEN_TRABAJO_TB(ID_ESTADO);
/
CREATE INDEX FIDE_ORDEN_TRABAJO_TB_FECHA_ASIGNACION_IDX ON FIDE_ORDEN_TRABAJO_TB(FECHA_ASIGNACION);
/
CREATE INDEX FIDE_ORDEN_TRABAJO_TB_FECHA_CIERRE_IDX ON FIDE_ORDEN_TRABAJO_TB(FECHA_CIERRE);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla puente entre órdenes de trabajo y empleados asignados
CREATE TABLE FIDE_ORDEN_EMPLEADO_TB (
    ID_ORDEN_TRABAJO NUMBER CONSTRAINT FIDE_ORDEN_EMPLEADO_TB_ID_ORDEN_TRABAJO_NN NOT NULL,
    ID_EMPLEADO NUMBER CONSTRAINT FIDE_ORDEN_EMPLEADO_TB_ID_EMPLEADO_NN NOT NULL,
    CONSTRAINT FIDE_ORDEN_EMPLEADO_TB_PK PRIMARY KEY (ID_ORDEN_TRABAJO, ID_EMPLEADO),
    CONSTRAINT FIDE_ORDEN_EMPLEADO_TB_ID_ORDEN_TRABAJO_FK FOREIGN KEY (ID_ORDEN_TRABAJO) REFERENCES FIDE_ORDEN_TRABAJO_TB(ID_ORDEN_TRABAJO),
    CONSTRAINT FIDE_ORDEN_EMPLEADO_TB_ID_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES FIDE_EMPLEADO_TB(ID_EMPLEADO)
);
/
CREATE INDEX FIDE_ORDEN_EMPLEADO_TB_ID_EMPLEADO_IDX ON FIDE_ORDEN_EMPLEADO_TB(ID_EMPLEADO);
/
CREATE INDEX FIDE_ORDEN_EMPLEADO_TB_ID_ORDEN_TRABAJO_IDX ON FIDE_ORDEN_EMPLEADO_TB(ID_ORDEN_TRABAJO);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla puente entre órdenes de trabajo y materiales utilizados
CREATE TABLE FIDE_ORDEN_INVENTARIO_TB (
    ID_ORDEN_TRABAJO NUMBER CONSTRAINT FIDE_ORDEN_INVENTARIO_TB_ID_ORDEN_TRABAJO_NN NOT NULL,
    ID_INVENTARIO NUMBER CONSTRAINT FIDE_ORDEN_INVENTARIO_TB_ID_INVENTARIO_NN NOT NULL,
    CONSTRAINT FIDE_ORDEN_INVENTARIO_TB_PK PRIMARY KEY (ID_ORDEN_TRABAJO, ID_INVENTARIO),
    CONSTRAINT FIDE_ORDEN_INVENTARIO_TB_ID_ORDEN_TRABAJO_FK FOREIGN KEY (ID_ORDEN_TRABAJO) REFERENCES FIDE_ORDEN_TRABAJO_TB(ID_ORDEN_TRABAJO),
    CONSTRAINT FIDE_ORDEN_INVENTARIO_TB_ID_INVENTARIO_FK FOREIGN KEY (ID_INVENTARIO) REFERENCES FIDE_INVENTARIO_TB(ID_INVENTARIO)
);
/
CREATE INDEX FIDE_ORDEN_INVENTARIO_TB_ID_INVENTARIO_IDX ON FIDE_ORDEN_INVENTARIO_TB(ID_INVENTARIO);
/
CREATE INDEX FIDE_ORDEN_INVENTARIO_TB_ID_ORDEN_TRABAJO_IDX ON FIDE_ORDEN_INVENTARIO_TB(ID_ORDEN_TRABAJO);
/

-- AUTORES: Integrantes del grupo #4
-- FECHA: 03/07/2026
-- Descripción: Tabla de movimientos de entrada y salida del inventario
CREATE TABLE FIDE_MOVIMIENTO_INVENTARIO_TB (
    ID_MOVIMIENTO_INVENTARIO NUMBER CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_TB_ID_MOVIMIENTO_INVENTARIO_NN NOT NULL,
    TIPO VARCHAR2(50) CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_TB_TIPO_NN NOT NULL,
    FECHA DATE CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_TB_FECHA_NN NOT NULL,
    CANTIDAD NUMBER(12,4) CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_TB_CANTIDAD_NN NOT NULL,
    MOTIVO VARCHAR2(255),
    ID_INVENTARIO NUMBER CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_TB_ID_INVENTARIO_NN NOT NULL,
    ID_ORDEN_TRABAJO NUMBER CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_TB_ID_ORDEN_TRABAJO_NN NOT NULL,
    ID_ESTADO NUMBER CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_TB_ID_ESTADO_NN NOT NULL,
    CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_TB_ID_MOVIMIENTO_INVENTARIO_PK PRIMARY KEY (ID_MOVIMIENTO_INVENTARIO),
    CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_TB_ID_INVENTARIO_FK FOREIGN KEY (ID_INVENTARIO) REFERENCES FIDE_INVENTARIO_TB(ID_INVENTARIO),
    CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_TB_ID_ORDEN_TRABAJO_FK FOREIGN KEY (ID_ORDEN_TRABAJO) REFERENCES FIDE_ORDEN_TRABAJO_TB(ID_ORDEN_TRABAJO),
    CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE INDEX FIDE_MOVIMIENTO_INVENTARIO_TB_ID_INVENTARIO_IDX ON FIDE_MOVIMIENTO_INVENTARIO_TB(ID_INVENTARIO);
/
CREATE INDEX FIDE_MOVIMIENTO_INVENTARIO_TB_ID_ORDEN_TRABAJO_IDX ON FIDE_MOVIMIENTO_INVENTARIO_TB(ID_ORDEN_TRABAJO);
/
CREATE INDEX FIDE_MOVIMIENTO_INVENTARIO_TB_ID_ESTADO_IDX ON FIDE_MOVIMIENTO_INVENTARIO_TB(ID_ESTADO);
/
CREATE INDEX FIDE_MOVIMIENTO_INVENTARIO_TB_FECHA_IDX ON FIDE_MOVIMIENTO_INVENTARIO_TB(FECHA);
/
CREATE INDEX FIDE_MOVIMIENTO_INVENTARIO_TB_TIPO_IDX ON FIDE_MOVIMIENTO_INVENTARIO_TB(TIPO);
/

COMMIT;
/
