TRUNCATE TABLE FIDE_MOVIMIENTO_INVENTARIO_TB;
TRUNCATE TABLE FIDE_ORDEN_INVENTARIO_TB;
TRUNCATE TABLE FIDE_ORDEN_EMPLEADO_TB;
TRUNCATE TABLE FIDE_DETALLE_FACTURA_PROVEEDOR_TB;
TRUNCATE TABLE FIDE_PAGO_TB;
TRUNCATE TABLE FIDE_DETALLE_FACTURA_TB;
TRUNCATE TABLE FIDE_DIRECCIONES_ABONADO_TB;
TRUNCATE TABLE FIDE_DIRECCIONES_EMPLEADO_TB;
TRUNCATE TABLE FIDE_DIRECCIONES_PROVEEDOR_TB;
TRUNCATE TABLE FIDE_CORREO_ABONADO_TB;
TRUNCATE TABLE FIDE_CORREO_EMPLEADO_TB;
TRUNCATE TABLE FIDE_CORREO_PROVEEDOR_TB;
TRUNCATE TABLE FIDE_TELEFONO_ABONADO_TB;
TRUNCATE TABLE FIDE_TELEFONO_EMPLEADO_TB;
TRUNCATE TABLE FIDE_TELEFONO_PROVEEDOR_TB;
TRUNCATE TABLE FIDE_PROVEEDOR_INVENTARIO_TB;
TRUNCATE TABLE FIDE_ALMACEN_INVENTARIO_TB;
TRUNCATE TABLE FIDE_ORDEN_TRABAJO_TB;
TRUNCATE TABLE FIDE_FACTURA_PROVEEDOR_TB;
TRUNCATE TABLE FIDE_FACTURA_TB;
TRUNCATE TABLE FIDE_INVENTARIO_TB;
TRUNCATE TABLE FIDE_PAIS_ABONADO_TB;
TRUNCATE TABLE FIDE_PROVINCIA_ABONADO_TB;
TRUNCATE TABLE FIDE_CANTON_ABONADO_TB;
TRUNCATE TABLE FIDE_DISTRITO_ABONADO_TB;
TRUNCATE TABLE FIDE_PAIS_EMPLEADO_TB;
TRUNCATE TABLE FIDE_PROVINCIA_EMPLEADO_TB;
TRUNCATE TABLE FIDE_CANTON_EMPLEADO_TB;
TRUNCATE TABLE FIDE_DISTRITO_EMPLEADO_TB;
TRUNCATE TABLE FIDE_PAIS_PROVEEDOR_TB;
TRUNCATE TABLE FIDE_PROVINCIA_PROVEEDOR_TB;
TRUNCATE TABLE FIDE_CANTON_PROVEEDOR_TB;
TRUNCATE TABLE FIDE_DISTRITO_PROVEEDOR_TB;
TRUNCATE TABLE FIDE_AVERIA_TB;
TRUNCATE TABLE FIDE_LECTURA_TB;
TRUNCATE TABLE FIDE_TARIFA_TB;
TRUNCATE TABLE FIDE_UNIDAD_MEDIDA_TB;
TRUNCATE TABLE FIDE_PROVEEDOR_TB;
TRUNCATE TABLE FIDE_MEDIDOR_TB;
TRUNCATE TABLE FIDE_TIPO_AVERIA_TB;
TRUNCATE TABLE FIDE_TIPO_ORDEN_TRABAJO_TB;
TRUNCATE TABLE FIDE_TIPO_MEDIDOR_TB;
TRUNCATE TABLE FIDE_ABONADO_TB;
TRUNCATE TABLE FIDE_SECTOR_TB;
TRUNCATE TABLE FIDE_EMPLEADO_TB;
TRUNCATE TABLE FIDE_METODO_PAGO_TB;
TRUNCATE TABLE FIDE_PUESTO_TB;
TRUNCATE TABLE FIDE_ESTADO_TB;



--DROPS


DROP TABLE FIDE_MOVIMIENTO_INVENTARIO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_ORDEN_INVENTARIO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_ORDEN_EMPLEADO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_DETALLE_FACTURA_PROVEEDOR_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PAGO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_DETALLE_FACTURA_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_DIRECCIONES_ABONADO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_DIRECCIONES_EMPLEADO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_DIRECCIONES_PROVEEDOR_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_CORREO_ABONADO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_CORREO_EMPLEADO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_CORREO_PROVEEDOR_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_TELEFONO_ABONADO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_TELEFONO_EMPLEADO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_TELEFONO_PROVEEDOR_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PROVEEDOR_INVENTARIO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_ALMACEN_INVENTARIO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_ORDEN_TRABAJO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_FACTURA_PROVEEDOR_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_FACTURA_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_INVENTARIO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PAIS_ABONADO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PROVINCIA_ABONADO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_CANTON_ABONADO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_DISTRITO_ABONADO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PAIS_EMPLEADO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PROVINCIA_EMPLEADO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_CANTON_EMPLEADO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_DISTRITO_EMPLEADO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PAIS_PROVEEDOR_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PROVINCIA_PROVEEDOR_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_CANTON_PROVEEDOR_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_DISTRITO_PROVEEDOR_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_AVERIA_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_LECTURA_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_TARIFA_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_UNIDAD_MEDIDA_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PROVEEDOR_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_MEDIDOR_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_TIPO_AVERIA_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_TIPO_ORDEN_TRABAJO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_TIPO_MEDIDOR_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_ABONADO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_SECTOR_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_EMPLEADO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_METODO_PAGO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PUESTO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_ESTADO_TB CASCADE CONSTRAINTS;




