-- AUTORES: Integrates del grupo #4
-- FECHA: 02/07/2026
-- Descripción: Creacion del perfil
CREATE PROFILE FIDE_PROYECTO_FINAL_PROF LIMIT
    SESSIONS_PER_USER 1
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_REUSE_MAX 3
    PASSWORD_LIFE_TIME 90
    PASSWORD_LOCK_TIME 1
    PASSWORD_GRACE_TIME 7
    PASSWORD_VERIFY_FUNCTION ADMIN.VERIFICA_PASSWORD; --está función es la que hicimos en clase
-- AUTORES: Integrates del grupo #4
-- FECHA: 02/07/2026
--Descripción: Crear un rol admin
CREATE ROLE FIDE_PROYECTO_ADMIN_ROL NOT IDENTIFIED;


-- AUTORES: Integrates del grupo #4
-- FECHA: 02/07/2026
-- Descripción: Dar privilegios al rol
GRANT RESOURCE TO FIDE_PROYECTO_ADMIN_ROL;
GRANT CREATE SESSION TO FIDE_PROYECTO_ADMIN_ROL;
GRANT CREATE TABLE TO FIDE_PROYECTO_ADMIN_ROL;


-- AUTORES: Integrates del grupo #4
-- FECHA: 02/07/2026
--Descripción: Crear usuario
CREATE USER FIDE_ASADA_ADMIN
IDENTIFIED BY A$ada2026_Fide
DEFAULT TABLESPACE FIDE_PROYECTO_FINAL_TBS
TEMPORARY TABLESPACE TEMP
PROFILE FIDE_PROYECTO_FINAL_PROF
QUOTA UNLIMITED ON FIDE_PROYECTO_FINAL_TBS;

-- AUTORES: Integrates del grupo #4
-- FECHA: 02/07/2026
--Descripción: Asignar el rol al usuario
GRANT FIDE_PROYECTO_ADMIN_ROL TO FIDE_ASADA_ADMIN;

-- AUTORES: Integrates del grupo #4
-- FECHA: 02/07/2026
--Descripción:Rol para el personal administrativo
CREATE ROLE FIDE_PROYECTO_ADMINISTRATIVO_ROL NOT IDENTIFIED;

--Rol para el personal operativo
CREATE ROLE FIDE_PROYECTO_OPERATIVO_ROL NOT IDENTIFIED;
--Rol para el personal de auditoría
CREATE ROLE FIDE_PROYECTO_AUDITORIA_ROL NOT IDENTIFIED;


-- AUTORES: Integrates del grupo #4
-- FECHA: 02/07/2026
--Permisos básicos a los roles
GRANT CREATE SESSION TO FIDE_PROYECTO_ADMINISTRATIVO_ROL;
GRANT CREATE SESSION TO FIDE_PROYECTO_OPERATIVO_ROL;
GRANT CREATE SESSION TO FIDE_PROYECTO_AUDITORIA_ROL;

-- AUTORES: Integrates del grupo #4
-- FECHA: 02/07/2026
--Crear usuarios
--Usuario Administrativo
CREATE USER FIDE_ASADA_ADMINISTRATIVO
IDENTIFIED BY A$ada2026_Fide
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
PROFILE FIDE_PROYECTO_FINAL_PROF
QUOTA UNLIMITED ON DATA;


-- AUTORES: Integrates del grupo #4
-- FECHA: 02/07/2026
--Usuario Operativo
CREATE USER FIDE_ASADA_OPERATIVO
IDENTIFIED BY A$ada2026_Fide
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
PROFILE FIDE_PROYECTO_FINAL_PROF
QUOTA UNLIMITED ON DATA;


-- AUTORES: Integrates del grupo #4
-- FECHA: 02/07/2026
--Usuario Auditoría
CREATE USER FIDE_ASADA_AUDITORIA
IDENTIFIED BY A$ada2026_Fide
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
PROFILE FIDE_PROYECTO_FINAL_PROF
QUOTA UNLIMITED ON DATA;

-- AUTORES: Integrates del grupo #4
-- FECHA: 02/07/2026
--Asignar roles a los usuarios
GRANT FIDE_PROYECTO_ADMINISTRATIVO_ROL TO FIDE_ASADA_ADMINISTRATIVO;

-- AUTORES: Integrates del grupo #4
-- FECHA: 02/07/2026
--Asignar roles a los usuarios
GRANT FIDE_PROYECTO_OPERATIVO_ROL TO FIDE_ASADA_OPERATIVO;

-- AUTORES: Integrates del grupo #4
-- FECHA: 02/07/2026
--Asignar roles a los usuarios
GRANT FIDE_PROYECTO_AUDITORIA_ROL TO FIDE_ASADA_AUDITORIA;
